package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"strconv"
	"strings"

	"github.com/savannahghi/scalarutils"
	"github.com/savannahghi/serverutils"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
	"github.com/savannahghi/empower-clinical/pkg/clinical/domain"
	"github.com/savannahghi/empower-clinical/pkg/clinical/presentation/graph/generated"
)

// CreateEpisodeOfCare is the resolver for the createEpisodeOfCare field.
func (r *mutationResolver) CreateEpisodeOfCare(ctx context.Context, episodeOfCare dto.EpisodeOfCareInput) (*dto.EpisodeOfCare, error) {
	r.CheckDependencies()
	return r.usecases.CreateEpisodeOfCare(ctx, episodeOfCare)
}

// PatchEpisodeOfCare is the resolver for the patchEpisodeOfCare field.
func (r *mutationResolver) PatchEpisodeOfCare(ctx context.Context, id string, episodeOfCare dto.EpisodeOfCareInput) (*dto.EpisodeOfCare, error) {
	r.CheckDependencies()
	return r.usecases.PatchEpisodeOfCare(ctx, id, episodeOfCare)
}

// EndEpisodeOfCare is the resolver for the endEpisodeOfCare field.
func (r *mutationResolver) EndEpisodeOfCare(ctx context.Context, id string) (*dto.EpisodeOfCare, error) {
	r.CheckDependencies()
	return r.usecases.EndEpisodeOfCare(ctx, id)
}

// StartEncounter is the resolver for the startEncounter field.
func (r *mutationResolver) StartEncounter(ctx context.Context, episodeID string) (string, error) {
	r.CheckDependencies()
	return r.usecases.StartEncounter(ctx, episodeID)
}

// PatchEncounter is the resolver for the patchEncounter field.
func (r *mutationResolver) PatchEncounter(ctx context.Context, encounterID string, input dto.EncounterInput) (*dto.Encounter, error) {
	r.CheckDependencies()
	return r.usecases.PatchEncounter(ctx, encounterID, input)
}

// EndEncounter is the resolver for the endEncounter field.
func (r *mutationResolver) EndEncounter(ctx context.Context, encounterID string) (bool, error) {
	r.CheckDependencies()
	return r.usecases.EndEncounter(ctx, encounterID)
}

// RecordTemperature is the resolver for the recordTemperature field.
func (r *mutationResolver) RecordTemperature(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordTemperature(ctx, input)
}

// RecordHeight is the resolver for the recordHeight field.
func (r *mutationResolver) RecordHeight(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordHeight(ctx, input)
}

// RecordWeight is the resolver for the recordWeight field.
func (r *mutationResolver) RecordWeight(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordWeight(ctx, input)
}

// RecordRespiratoryRate is the resolver for the recordRespiratoryRate field.
func (r *mutationResolver) RecordRespiratoryRate(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordRespiratoryRate(ctx, input)
}

// RecordPulseRate is the resolver for the recordPulseRate field.
func (r *mutationResolver) RecordPulseRate(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordPulseRate(ctx, input)
}

// RecordBloodPressure is the resolver for the recordBloodPressure field.
func (r *mutationResolver) RecordBloodPressure(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordBloodPressure(ctx, input)
}

// RecordBmi is the resolver for the recordBMI field.
func (r *mutationResolver) RecordBmi(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordBMI(ctx, input)
}

// RecordViralLoad is the resolver for the recordViralLoad field.
func (r *mutationResolver) RecordViralLoad(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()

	return r.usecases.RecordViralLoad(ctx, input)
}

// RecordMuac is the resolver for the recordMUAC field.
func (r *mutationResolver) RecordMuac(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordMuac(ctx, input)
}

// RecordOxygenSaturation is the resolver for the recordOxygenSaturation field.
func (r *mutationResolver) RecordOxygenSaturation(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordOxygenSaturation(ctx, input)
}

// RecordBloodSugar is the resolver for the recordBloodSugar field.
func (r *mutationResolver) RecordBloodSugar(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordBloodSugar(ctx, input)
}

// RecordLastMenstrualPeriod is the resolver for the recordLastMenstrualPeriod field.
func (r *mutationResolver) RecordLastMenstrualPeriod(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordLastMenstrualPeriod(ctx, input)
}

// RecordDiastolicBloodPressure is the resolver for the recordDiastolicBloodPressure field.
func (r *mutationResolver) RecordDiastolicBloodPressure(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordDiastolicBloodPressure(ctx, input)
}

// RecordColposcopy is the resolver for the recordColposcopy field.
func (r *mutationResolver) RecordColposcopy(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	return r.usecases.RecordColposcopy(ctx, input)
}

// RecordVia is the resolver for the recordVIA field.
func (r *mutationResolver) RecordVia(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordVIA(ctx, input)
}

// RecordImmunoHistoChemistry is the resolver for the recordImmunoHistoChemistry field.
func (r *mutationResolver) RecordImmunoHistoChemistry(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	return r.usecases.RecordImmunoHistoChemistry(ctx, input)
}

// RecordPostCoitalBleeding is the resolver for the recordPostCoitalBleeding field.
func (r *mutationResolver) RecordPostCoitalBleeding(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	return r.usecases.RecordPostCoitalBleeding(ctx, input)
}

// RecordHistoryOfPresentIllness is the resolver for the recordHistoryOfPresentIllness field.
func (r *mutationResolver) RecordHistoryOfPresentIllness(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	return r.usecases.RecordHistoryOfPresentIllness(ctx, input)
}

// RecordPastMedicalAndSurgicalHistory is the resolver for the recordPastMedicalAndSurgicalHistory field.
func (r *mutationResolver) RecordPastMedicalAndSurgicalHistory(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	return r.usecases.RecordPastMedicalAndSurgicalHistory(ctx, input)
}

// RecordFamilyAndSocialHistory is the resolver for the recordFamilyAndSocialHistory field.
func (r *mutationResolver) RecordFamilyAndSocialHistory(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	return r.usecases.RecordFamilyAndSocialHistory(ctx, input)
}

// RecordHpv is the resolver for the recordHPV field.
func (r *mutationResolver) RecordHpv(ctx context.Context, input dto.ObservationInput) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.RecordHPV(ctx, input)
}

// CreatePatient is the resolver for the createPatient field.
func (r *mutationResolver) CreatePatient(ctx context.Context, input dto.PatientInput) (*dto.Patient, error) {
	r.CheckDependencies()
	return r.usecases.CreatePatient(ctx, input)
}

// PatchPatient is the resolver for the patchPatient field.
func (r *mutationResolver) PatchPatient(ctx context.Context, id string, input dto.PatientInput) (*dto.Patient, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatient(ctx, id, input)
}

// DeletePatient is the resolver for the deletePatient field.
func (r *mutationResolver) DeletePatient(ctx context.Context, id string) (bool, error) {
	r.CheckDependencies()
	return r.usecases.DeletePatient(ctx, id)
}

// CreateCondition is the resolver for the createCondition field.
func (r *mutationResolver) CreateCondition(ctx context.Context, input dto.ConditionInput) (*dto.Condition, error) {
	r.CheckDependencies()
	return r.usecases.CreateCondition(ctx, input)
}

// CreateAllergyIntolerance is the resolver for the createAllergyIntolerance field.
func (r *mutationResolver) CreateAllergyIntolerance(ctx context.Context, input dto.AllergyInput) (*dto.Allergy, error) {
	return r.usecases.CreateAllergyIntolerance(ctx, input)
}

// PatchPatientHeight is the resolver for the patchHeight field.
func (r *mutationResolver) PatchPatientHeight(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientHeight(ctx, id, value)
}

// PatchPatientWeight is the resolver for the patchWeight field.
func (r *mutationResolver) PatchPatientWeight(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientWeight(ctx, id, value)
}

// PatchPatientBmi is the resolver for the patchPatientBMI field.
func (r *mutationResolver) PatchPatientBmi(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientBMI(ctx, id, value)
}

// PatchPatientTemperature is the resolver for the patchPatientTemperature field.
func (r *mutationResolver) PatchPatientTemperature(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientTemperature(ctx, id, value)
}

// PatchPatientDiastolicBloodPressure is the resolver for the patchPatientDiastolicBloodPressure field.
func (r *mutationResolver) PatchPatientDiastolicBloodPressure(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientDiastolicBloodPressure(ctx, id, value)
}

// PatchPatientSystolicBloodPressure is the resolver for the patchPatientSystolicBloodPressure field.
func (r *mutationResolver) PatchPatientSystolicBloodPressure(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientSystolicBloodPressure(ctx, id, value)
}

// PatchPatientRespiratoryRate is the resolver for the patchPatientRespiratoryRate field.
func (r *mutationResolver) PatchPatientRespiratoryRate(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientRespiratoryRate(ctx, id, value)
}

// PatchPatientOxygenSaturation is the resolver for the patchPatientOxygenSaturation field.
func (r *mutationResolver) PatchPatientOxygenSaturation(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientOxygenSaturation(ctx, id, value)
}

// PatchPatientPulseRate is the resolver for the PatchPatientPulseRate field.
func (r *mutationResolver) PatchPatientPulseRate(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientPulseRate(ctx, id, value)
}

// PatchPatientViralLoad is the resolver for the PatchPatientViralLoad field.
func (r *mutationResolver) PatchPatientViralLoad(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientViralLoad(ctx, id, value)
}

// PatchPatientMuac is the resolver for the patchPatientMuac field.
func (r *mutationResolver) PatchPatientMuac(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientMuac(ctx, id, value)
}

// PatchPatientLastMenstrualPeriod is the resolver for the patchPatientLastMenstrualPeriod field.
func (r *mutationResolver) PatchPatientLastMenstrualPeriod(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientLastMenstrualPeriod(ctx, id, value)
}

// PatchPatientBloodSugar is the resolver for the patchPatientBloodSugar field.
func (r *mutationResolver) PatchPatientBloodSugar(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.PatchPatientBloodSugar(ctx, id, value)
}

// PatchObservation is the resolver for the patchObservation field.
func (r *mutationResolver) PatchObservation(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()

	return r.usecases.PatchPatientObservations(ctx, id, value)
}

// RecordConsent is the resolver for the recordConsent field.
func (r *mutationResolver) RecordConsent(ctx context.Context, input dto.ConsentInput) (*dto.ConsentOutput, error) {
	return r.usecases.RecordConsent(ctx, input)
}

// CreateQuestionnaireResponse is the resolver for the createQuestionnaireResponse field.
func (r *mutationResolver) CreateQuestionnaireResponse(ctx context.Context, questionnaireID string, encounterID string, input dto.QuestionnaireResponse) (*dto.QuestionnaireReviewSummary, error) {
	return r.usecases.CreateQuestionnaireResponse(ctx, questionnaireID, encounterID, input)
}

// RecordMammographyResult is the resolver for the recordMammographyResult field.
func (r *mutationResolver) RecordMammographyResult(ctx context.Context, input dto.DiagnosticReportInput) (*dto.DiagnosticReport, error) {
	return r.usecases.RecordMammographyResult(ctx, input)
}

// RecordBiopsy is the resolver for the recordBiopsy field.
func (r *mutationResolver) RecordBiopsy(ctx context.Context, input dto.DiagnosticReportInput) (*dto.DiagnosticReport, error) {
	return r.usecases.RecordBiopsy(ctx, input)
}

// RecordMri is the resolver for the recordMRI field.
func (r *mutationResolver) RecordMri(ctx context.Context, input dto.DiagnosticReportInput) (*dto.DiagnosticReport, error) {
	return r.usecases.RecordMRI(ctx, input)
}

// RecordUltrasound is the resolver for the recordUltrasound field.
func (r *mutationResolver) RecordUltrasound(ctx context.Context, input dto.DiagnosticReportInput) (*dto.DiagnosticReport, error) {
	return r.usecases.RecordUltrasound(ctx, input)
}

// RecordCbe is the resolver for the recordCBE field.
func (r *mutationResolver) RecordCbe(ctx context.Context, input dto.DiagnosticReportInput) (*dto.DiagnosticReport, error) {
	return r.usecases.RecordCBE(ctx, &input)
}

// RecordPapSmear is the resolver for the recordPapSmear field.
func (r *mutationResolver) RecordPapSmear(ctx context.Context, input dto.DiagnosticReportInput) (*dto.DiagnosticReport, error) {
	r.CheckDependencies()

	return r.usecases.RecordPapSmear(ctx, &input)
}

// RecordPsa is the resolver for the recordPSA field.
func (r *mutationResolver) RecordPsa(ctx context.Context, input dto.PSAInput) (*dto.DiagnosticReport, error) {
	r.CheckDependencies()
	return r.usecases.RecordPSA(ctx, &input)
}

// UpdateTestResults is the resolver for the updateTestResults field.
func (r *mutationResolver) UpdateTestResults(ctx context.Context, id string, value string) (*dto.Observation, error) {
	r.CheckDependencies()
	return r.usecases.UpdateTestResults(ctx, id, value)
}

// GetEncounterAssociatedResources is the resolver for the getEncounterAssociatedResources field.
func (r *mutationResolver) GetEncounterAssociatedResources(ctx context.Context, encounterID string) (*dto.EncounterAssociatedResourceOutput, error) {
	return r.usecases.GetEncounterAssociatedResources(ctx, encounterID)
}

// ReferPatient is the resolver for the referPatient field.
func (r *mutationResolver) ReferPatient(ctx context.Context, input dto.ReferralInput) (*dto.ServiceRequest, error) {
	return r.usecases.ReferPatient(ctx, &input)
}

// CreateReferral is the resolver for the createReferral field.
func (r *mutationResolver) CreateReferral(ctx context.Context, input dto.CreateReferralInput) (*dto.ServiceRequest, error) {
	return r.usecases.CreateReferral(ctx, &input)
}

// CreateTestOrder is the resolver for the createTestOrder field.
func (r *mutationResolver) CreateTestOrder(ctx context.Context, input dto.TestOrder) (*dto.ServiceRequest, error) {
	return r.usecases.CreateTestOrder(ctx, &input)
}

// CreateLabOrderResult is the resolver for the createLabOrderResult field.
func (r *mutationResolver) CreateLabOrderResult(ctx context.Context, input dto.TestOrderResult) (*dto.DiagnosticReport, error) {
	return r.usecases.CreateLabOrderResult(ctx, &input)
}

// ShareReferralForm is the resolver for the shareReferralForm field.
func (r *mutationResolver) ShareReferralForm(ctx context.Context, serviceRequestID string, workstationID string, branchID string) (bool, error) {
	r.CheckDependencies()

	return r.usecases.ShareReferralForm(ctx, &dto.ShareReferralFormInput{
		ServiceRequestID: serviceRequestID,
		WorkstationID:    workstationID,
		BranchID:         branchID,
	})
}

// EndScreening is the resolver for the endScreening field.
func (r *mutationResolver) EndScreening(ctx context.Context, encounterID string) (bool, error) {
	return r.usecases.EndScreening(ctx, encounterID)
}

// ScheduleAppointment is the resolver for the scheduleAppointment field.
func (r *mutationResolver) ScheduleAppointment(ctx context.Context, input *dto.ScheduleAppointmentInput, headersInput dto.AdvantageHeaders) (bool, error) {
	return r.usecases.ScheduleAppointment(ctx, input, &headersInput)
}

// AddTestResultsLater is the resolver for the addTestResultsLater field.
func (r *mutationResolver) AddTestResultsLater(ctx context.Context, taskInput dto.TaskInput) (*dto.TaskOutput, error) {
	r.CheckDependencies()

	return r.usecases.AddTestResultsLater(ctx, &taskInput)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input dto.PatchTaskInput) (bool, error) {
	r.CheckDependencies()

	return r.usecases.UpdateTask(ctx, id, &input)
}

// CreatePrescription is the resolver for the createPrescription field.
func (r *mutationResolver) CreatePrescription(ctx context.Context, input dto.PrescriptionInput) ([]*dto.MedicationRequestOutput, error) {
	r.CheckDependencies()
	return r.usecases.CreatePrescription(ctx, input)
}

// UpdateMedicationRequest is the resolver for the updateMedicationRequest field.
func (r *mutationResolver) UpdateMedicationRequest(ctx context.Context, id string, value domain.MedicationRequestStatus) (*dto.MedicationRequestOutput, error) {
	r.CheckDependencies()
	return r.usecases.PatchMedicationRequests(ctx, id, value)
}

// RecordTestResults is the resolver for the recordTestResults field.
func (r *mutationResolver) RecordTestResults(ctx context.Context, input dto.TestResultInput) (*dto.DiagnosticReport, error) {
	r.CheckDependencies()
	return r.usecases.RecordTestResult(ctx, input)
}

// PatientHealthTimeline is the resolver for the patientHealthTimeline field.
func (r *queryResolver) PatientHealthTimeline(ctx context.Context, input dto.HealthTimelineInput) (*dto.HealthTimeline, error) {
	r.CheckDependencies()

	return r.usecases.GetPatientTimeline(ctx, input.PatientID, &dto.PatientEverythingFilterParams{
		Count: strconv.Itoa(input.Limit),
		Type:  strings.Join(input.Type, ","),
	})
}

// GetMedicalData is the resolver for the getMedicalData field.
func (r *queryResolver) GetMedicalData(ctx context.Context, patientID string) (*dto.MedicalData, error) {
	r.CheckDependencies()

	return r.usecases.GetMedicalData(ctx, patientID)
}

// GetEpisodeOfCare is the resolver for the getEpisodeOfCare field.
func (r *queryResolver) GetEpisodeOfCare(ctx context.Context, id string) (*dto.EpisodeOfCare, error) {
	r.CheckDependencies()
	return r.usecases.GetEpisodeOfCare(ctx, id)
}

// ListPatientConditions is the resolver for the listPatientConditions field.
func (r *queryResolver) ListPatientConditions(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ConditionConnection, error) {
	r.CheckDependencies()
	return r.usecases.ListPatientConditions(ctx, patientID, encounterID, date, "", pagination)
}

// ListPatientCompositions is the resolver for the listPatientCompositions field.
func (r *queryResolver) ListPatientCompositions(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.CompositionConnection, error) {
	r.CheckDependencies()
	return r.usecases.ListPatientCompositions(ctx, patientID, encounterID, date, pagination)
}

// ListPatientEncounters is the resolver for the listPatientEncounters field.
func (r *queryResolver) ListPatientEncounters(ctx context.Context, patientID string, pagination dto.Pagination) (*dto.EncounterConnection, error) {
	r.CheckDependencies()

	return r.usecases.ListPatientEncounters(ctx, patientID, &pagination)
}

// GetPatientTemperatureEntries is the resolver for the getPatientTemperatureEntries field.
func (r *queryResolver) GetPatientTemperatureEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientTemperatureEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientBloodPressureEntries is the resolver for the getPatientBloodPressureEntries field.
func (r *queryResolver) GetPatientBloodPressureEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientBloodPressureEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientHeightEntries is the resolver for the getPatientHeightEntries field.
func (r *queryResolver) GetPatientHeightEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetPatientHeightEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientRespiratoryRateEntries is the resolver for the getPatientRespiratoryRateEntries field.
func (r *queryResolver) GetPatientRespiratoryRateEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientRespiratoryRateEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientPulseRateEntries is the resolver for the GetPatientPulseRateEntries field.
func (r *queryResolver) GetPatientPulseRateEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetPatientPulseRateEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientBMIEntries is the resolver for the getPatientBMIEntries field.
func (r *queryResolver) GetPatientBMIEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientBMIEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientWeightEntries is the resolver for the getPatientWeightEntries field.
func (r *queryResolver) GetPatientWeightEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetPatientWeightEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientMuacEntries is the resolver for the getPatientMuacEntries field.
func (r *queryResolver) GetPatientMuacEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientMuacEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientOxygenSaturationEntries is the resolver for the getPatientOxygenSaturationEntries field.
func (r *queryResolver) GetPatientOxygenSaturationEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientOxygenSaturationEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientViralLoad is the resolver for the getPatientViralLoad field.
func (r *queryResolver) GetPatientViralLoad(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()

	return r.usecases.GetPatientViralLoad(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientBloodSugarEntries is the resolver for the getPatientBloodSugarEntries field.
func (r *queryResolver) GetPatientBloodSugarEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientBloodSugarEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientLastMenstrualPeriodEntries is the resolver for the GetPatientLastMenstrualPeriodEntries field.
func (r *queryResolver) GetPatientLastMenstrualPeriodEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientLastMenstrualPeriodEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientDiastolicBloodPressureEntries is the resolver for the getPatientDiastolicBloodPressureEntries field.
func (r *queryResolver) GetPatientDiastolicBloodPressureEntries(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	r.CheckDependencies()
	return r.usecases.GetPatientDiastolicBloodPressureEntries(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientImmunoHistoChemistryRecords is the resolver for the getPatientImmunoHistoChemistryRecords field.
func (r *queryResolver) GetPatientImmunoHistoChemistryRecords(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetPatientImmunoHistoChemistryRecords(ctx, patientID, encounterID, date, &pagination)
}

// GetPatientPostCoitalBleedingRecords is the resolver for the getPatientPostCoitalBleedingRecords field.
func (r *queryResolver) GetPatientPostCoitalBleedingRecords(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetPatientPostCoitalBleedingRecords(ctx, patientID, encounterID, date, &pagination)
}

// ListObservations is the resolver for the listObservations field.
func (r *queryResolver) ListObservations(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, category *dto.ObservationCategory, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.ListObservations(ctx, patientID, encounterID, date, category, pagination)
}

// SearchAllergy is the resolver for the searchAllergy field.
func (r *queryResolver) SearchAllergy(ctx context.Context, name string, pagination dto.Pagination) (*dto.TerminologyConnection, error) {
	r.CheckDependencies()

	return r.usecases.SearchAllergy(ctx, name, pagination)
}

// GetAllergy is the resolver for the getAllergy field.
func (r *queryResolver) GetAllergy(ctx context.Context, id string) (*dto.Allergy, error) {
	r.CheckDependencies()

	return r.usecases.GetAllergyIntolerance(ctx, id)
}

// ListPatientAllergies is the resolver for the listPatientAllergies field.
func (r *queryResolver) ListPatientAllergies(ctx context.Context, patientID string, pagination dto.Pagination) (*dto.AllergyConnection, error) {
	r.CheckDependencies()

	return r.usecases.ListPatientAllergies(ctx, patientID, pagination)
}

// ListPatientMedia is the resolver for the listPatientMedia field.
func (r *queryResolver) ListPatientMedia(ctx context.Context, encounterID string, serviceRequestID string, pagination dto.Pagination) (*dto.MediaConnection, error) {
	r.CheckDependencies()

	return r.usecases.ListPatientMedia(ctx, encounterID, serviceRequestID, pagination)
}

// GetRiskAssessment is the resolver for the getRiskAssessment field.
func (r *queryResolver) GetRiskAssessment(ctx context.Context, searchID *string, riskAssessmentFilter dto.RiskAssessmentFilterInput, pagination serverutils.PaginationInput) (*dto.RiskAssessmentConnection, error) {
	r.CheckDependencies()

	return r.usecases.ListRiskAssessment(ctx, *searchID, &riskAssessmentFilter, pagination)
}

// GetScreeningReport is the resolver for the getScreeningReport field.
func (r *queryResolver) GetScreeningReport(ctx context.Context, encounterID string) (*dto.ScreeningReport, error) {
	r.CheckDependencies()

	return r.usecases.GetScreeningReport(ctx, encounterID, domain.ServiceRequestStatusActive)
}

// ListTask is the resolver for the listTask field.
func (r *queryResolver) ListTask(ctx context.Context, filterInput dto.TaskFilterInput, pagination dto.Pagination) (*dto.TaskOutputConnection, error) {
	r.CheckDependencies()

	return r.usecases.ListTasks(ctx, &filterInput, pagination)
}

// ListMedicationRequests is the resolver for the listMedicationRequests field.
func (r *queryResolver) ListMedicationRequests(ctx context.Context, filterInput dto.MedicationRequestFilterInput, pagination dto.Pagination) (*dto.MedicationRequestConnection, error) {
	r.CheckDependencies()
	return r.usecases.ListMedicationRequests(ctx, &filterInput, pagination)
}

// GetPatientReferralDetails is the resolver for the getPatientReferralDetails field.
func (r *queryResolver) GetPatientReferralDetails(ctx context.Context, patientID *string, pagination dto.Pagination) (*dto.ReferralDetailConnection, error) {
	return r.usecases.GetPatientReferrals(ctx, &dto.ReferralSearchInput{
		PatientID:   patientID,
		EncounterID: nil,
		Pagination:  &pagination,
		Status:      "",
	})
}

// GetTaskByID is the resolver for the getTaskByID field.
func (r *queryResolver) GetTaskByID(ctx context.Context, taskID string) (*dto.TaskOutput, error) {
	r.CheckDependencies()

	return r.usecases.GetTaskByID(ctx, taskID)
}

// GetPatientReferralDetailsByID is the resolver for the getPatientReferralDetailsByID field.
func (r *queryResolver) GetPatientReferralDetailsByID(ctx context.Context, serviceRequestID string) (*domain.PatientReferralDetails, error) {
	return r.usecases.GetPatientReferralDetails(ctx, serviceRequestID)
}

// ListLabOrders is the resolver for the listLabOrders field.
func (r *queryResolver) ListLabOrders(ctx context.Context, filterInput *dto.ServiceRequestFilterInput, pagination dto.Pagination) (*dto.ServiceRequestOutputConnection, error) {
	r.CheckDependencies()

	return r.usecases.ListLabOrders(ctx, filterInput, pagination)
}

// SimpleQuestionnaireResponse is the resolver for the simpleQuestionnaireResponse field.
func (r *queryResolver) SimpleQuestionnaireResponse(ctx context.Context, questionnaireResponseID string) ([]*domain.SimpleQuestionnaireResponse, error) {
	return r.usecases.SimpleQuestionnaireResponse(ctx, questionnaireResponseID)
}

// GetLabOrderByID is the resolver for the getLabOrderByID field.
func (r *queryResolver) GetLabOrderByID(ctx context.Context, serviceRequestID string) (*dto.ServiceRequest, error) {
	return r.usecases.GetLabOrder(ctx, serviceRequestID)
}

// FetchMedicationRequestByID is the resolver for the fetchMedicationRequestByID field.
func (r *queryResolver) FetchMedicationRequestByID(ctx context.Context, medicationRequestID string) (*dto.MedicationRequestOutput, error) {
	r.CheckDependencies()
	return r.usecases.FetchMedicationRequestByID(ctx, medicationRequestID)
}

// GetHistoryOfPresentIllness is the resolver for the getHistoryOfPresentIllness field.
func (r *queryResolver) GetHistoryOfPresentIllness(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetHistoryOfPresentIllness(ctx, patientID, encounterID, date, &pagination)
}

// GetPastMedicalAndSurgicalHistory is the resolver for the getPastMedicalAndSurgicalHistory field.
func (r *queryResolver) GetPastMedicalAndSurgicalHistory(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetPastMedicalAndSurgicalHistory(ctx, patientID, encounterID, date, &pagination)
}

// GetFamilyAndSocialHistory is the resolver for the getFamilyAndSocialHistory field.
func (r *queryResolver) GetFamilyAndSocialHistory(ctx context.Context, patientID string, encounterID *string, date *scalarutils.Date, pagination dto.Pagination) (*dto.ObservationConnection, error) {
	return r.usecases.GetFamilyAndSocialHistory(ctx, patientID, encounterID, date, &pagination)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
