package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"

	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
	"github.com/savannahghi/empower-clinical/pkg/clinical/presentation/graph/generated"
)

// FindQuestionnaireByID is the resolver for the findQuestionnaireByID field.
func (r *entityResolver) FindQuestionnaireByID(ctx context.Context, id string) (*dto.Questionnaire, error) {
	panic(fmt.Errorf("not implemented: FindQuestionnaireByID - findQuestionnaireByID"))
}

// FindServiceRequestByID is the resolver for the findServiceRequestByID field.
func (r *entityResolver) FindServiceRequestByID(ctx context.Context, id string) (*dto.ServiceRequest, error) {
	panic(fmt.Errorf("not implemented: FindServiceRequestByID - findServiceRequestByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
