// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
)

// NewMockHapiFHIRImplementation creates a new instance of MockHapiFHIRImplementation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHapiFHIRImplementation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHapiFHIRImplementation {
	mock := &MockHapiFHIRImplementation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHapiFHIRImplementation is an autogenerated mock type for the HapiFHIRImplementation type
type MockHapiFHIRImplementation struct {
	mock.Mock
}

type MockHapiFHIRImplementation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHapiFHIRImplementation) EXPECT() *MockHapiFHIRImplementation_Expecter {
	return &MockHapiFHIRImplementation_Expecter{mock: &_m.Mock}
}

// CreateFHIRResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) CreateFHIRResource(ctx context.Context, resourceType string, payload map[string]interface{}, resource interface{}) error {
	ret := _mock.Called(ctx, resourceType, payload, resource)

	if len(ret) == 0 {
		panic("no return value specified for CreateFHIRResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, resourceType, payload, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_CreateFHIRResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFHIRResource'
type MockHapiFHIRImplementation_CreateFHIRResource_Call struct {
	*mock.Call
}

// CreateFHIRResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - payload map[string]interface{}
//   - resource interface{}
func (_e *MockHapiFHIRImplementation_Expecter) CreateFHIRResource(ctx interface{}, resourceType interface{}, payload interface{}, resource interface{}) *MockHapiFHIRImplementation_CreateFHIRResource_Call {
	return &MockHapiFHIRImplementation_CreateFHIRResource_Call{Call: _e.mock.On("CreateFHIRResource", ctx, resourceType, payload, resource)}
}

func (_c *MockHapiFHIRImplementation_CreateFHIRResource_Call) Run(run func(ctx context.Context, resourceType string, payload map[string]interface{}, resource interface{})) *MockHapiFHIRImplementation_CreateFHIRResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_CreateFHIRResource_Call) Return(err error) *MockHapiFHIRImplementation_CreateFHIRResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_CreateFHIRResource_Call) RunAndReturn(run func(ctx context.Context, resourceType string, payload map[string]interface{}, resource interface{}) error) *MockHapiFHIRImplementation_CreateFHIRResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFHIRResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) DeleteFHIRResource(ctx context.Context, resourceType string, fhirResourceID string) error {
	ret := _mock.Called(ctx, resourceType, fhirResourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFHIRResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, resourceType, fhirResourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_DeleteFHIRResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFHIRResource'
type MockHapiFHIRImplementation_DeleteFHIRResource_Call struct {
	*mock.Call
}

// DeleteFHIRResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - fhirResourceID string
func (_e *MockHapiFHIRImplementation_Expecter) DeleteFHIRResource(ctx interface{}, resourceType interface{}, fhirResourceID interface{}) *MockHapiFHIRImplementation_DeleteFHIRResource_Call {
	return &MockHapiFHIRImplementation_DeleteFHIRResource_Call{Call: _e.mock.On("DeleteFHIRResource", ctx, resourceType, fhirResourceID)}
}

func (_c *MockHapiFHIRImplementation_DeleteFHIRResource_Call) Run(run func(ctx context.Context, resourceType string, fhirResourceID string)) *MockHapiFHIRImplementation_DeleteFHIRResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_DeleteFHIRResource_Call) Return(err error) *MockHapiFHIRImplementation_DeleteFHIRResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_DeleteFHIRResource_Call) RunAndReturn(run func(ctx context.Context, resourceType string, fhirResourceID string) error) *MockHapiFHIRImplementation_DeleteFHIRResource_Call {
	_c.Call.Return(run)
	return _c
}

// FHIRPathPatch provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) FHIRPathPatch(ctx context.Context, resourceType string, resourceID string, payload map[string]interface{}, resource interface{}) error {
	ret := _mock.Called(ctx, resourceType, resourceID, payload, resource)

	if len(ret) == 0 {
		panic("no return value specified for FHIRPathPatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, payload, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_FHIRPathPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FHIRPathPatch'
type MockHapiFHIRImplementation_FHIRPathPatch_Call struct {
	*mock.Call
}

// FHIRPathPatch is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - resourceID string
//   - payload map[string]interface{}
//   - resource interface{}
func (_e *MockHapiFHIRImplementation_Expecter) FHIRPathPatch(ctx interface{}, resourceType interface{}, resourceID interface{}, payload interface{}, resource interface{}) *MockHapiFHIRImplementation_FHIRPathPatch_Call {
	return &MockHapiFHIRImplementation_FHIRPathPatch_Call{Call: _e.mock.On("FHIRPathPatch", ctx, resourceType, resourceID, payload, resource)}
}

func (_c *MockHapiFHIRImplementation_FHIRPathPatch_Call) Run(run func(ctx context.Context, resourceType string, resourceID string, payload map[string]interface{}, resource interface{})) *MockHapiFHIRImplementation_FHIRPathPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		var arg4 interface{}
		if args[4] != nil {
			arg4 = args[4].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_FHIRPathPatch_Call) Return(err error) *MockHapiFHIRImplementation_FHIRPathPatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_FHIRPathPatch_Call) RunAndReturn(run func(ctx context.Context, resourceType string, resourceID string, payload map[string]interface{}, resource interface{}) error) *MockHapiFHIRImplementation_FHIRPathPatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetFHIRResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) GetFHIRResource(ctx context.Context, resourceType string, fhirResourceID string, resource interface{}) error {
	ret := _mock.Called(ctx, resourceType, fhirResourceID, resource)

	if len(ret) == 0 {
		panic("no return value specified for GetFHIRResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = returnFunc(ctx, resourceType, fhirResourceID, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_GetFHIRResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFHIRResource'
type MockHapiFHIRImplementation_GetFHIRResource_Call struct {
	*mock.Call
}

// GetFHIRResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - fhirResourceID string
//   - resource interface{}
func (_e *MockHapiFHIRImplementation_Expecter) GetFHIRResource(ctx interface{}, resourceType interface{}, fhirResourceID interface{}, resource interface{}) *MockHapiFHIRImplementation_GetFHIRResource_Call {
	return &MockHapiFHIRImplementation_GetFHIRResource_Call{Call: _e.mock.On("GetFHIRResource", ctx, resourceType, fhirResourceID, resource)}
}

func (_c *MockHapiFHIRImplementation_GetFHIRResource_Call) Run(run func(ctx context.Context, resourceType string, fhirResourceID string, resource interface{})) *MockHapiFHIRImplementation_GetFHIRResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_GetFHIRResource_Call) Return(err error) *MockHapiFHIRImplementation_GetFHIRResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_GetFHIRResource_Call) RunAndReturn(run func(ctx context.Context, resourceType string, fhirResourceID string, resource interface{}) error) *MockHapiFHIRImplementation_GetFHIRResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetPatientEverything provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) GetPatientEverything(ctx context.Context, patientFhirID string, searchParams map[string]interface{}, bundle interface{}) error {
	ret := _mock.Called(ctx, patientFhirID, searchParams, bundle)

	if len(ret) == 0 {
		panic("no return value specified for GetPatientEverything")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, patientFhirID, searchParams, bundle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_GetPatientEverything_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPatientEverything'
type MockHapiFHIRImplementation_GetPatientEverything_Call struct {
	*mock.Call
}

// GetPatientEverything is a helper method to define mock.On call
//   - ctx context.Context
//   - patientFhirID string
//   - searchParams map[string]interface{}
//   - bundle interface{}
func (_e *MockHapiFHIRImplementation_Expecter) GetPatientEverything(ctx interface{}, patientFhirID interface{}, searchParams interface{}, bundle interface{}) *MockHapiFHIRImplementation_GetPatientEverything_Call {
	return &MockHapiFHIRImplementation_GetPatientEverything_Call{Call: _e.mock.On("GetPatientEverything", ctx, patientFhirID, searchParams, bundle)}
}

func (_c *MockHapiFHIRImplementation_GetPatientEverything_Call) Run(run func(ctx context.Context, patientFhirID string, searchParams map[string]interface{}, bundle interface{})) *MockHapiFHIRImplementation_GetPatientEverything_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_GetPatientEverything_Call) Return(err error) *MockHapiFHIRImplementation_GetPatientEverything_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_GetPatientEverything_Call) RunAndReturn(run func(ctx context.Context, patientFhirID string, searchParams map[string]interface{}, bundle interface{}) error) *MockHapiFHIRImplementation_GetPatientEverything_Call {
	_c.Call.Return(run)
	return _c
}

// PatchFHIRResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) PatchFHIRResource(ctx context.Context, resourceType string, resourceID string, payload interface{}, resource interface{}) error {
	ret := _mock.Called(ctx, resourceType, resourceID, payload, resource)

	if len(ret) == 0 {
		panic("no return value specified for PatchFHIRResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, payload, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_PatchFHIRResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchFHIRResource'
type MockHapiFHIRImplementation_PatchFHIRResource_Call struct {
	*mock.Call
}

// PatchFHIRResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - resourceID string
//   - payload interface{}
//   - resource interface{}
func (_e *MockHapiFHIRImplementation_Expecter) PatchFHIRResource(ctx interface{}, resourceType interface{}, resourceID interface{}, payload interface{}, resource interface{}) *MockHapiFHIRImplementation_PatchFHIRResource_Call {
	return &MockHapiFHIRImplementation_PatchFHIRResource_Call{Call: _e.mock.On("PatchFHIRResource", ctx, resourceType, resourceID, payload, resource)}
}

func (_c *MockHapiFHIRImplementation_PatchFHIRResource_Call) Run(run func(ctx context.Context, resourceType string, resourceID string, payload interface{}, resource interface{})) *MockHapiFHIRImplementation_PatchFHIRResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 interface{}
		if args[4] != nil {
			arg4 = args[4].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_PatchFHIRResource_Call) Return(err error) *MockHapiFHIRImplementation_PatchFHIRResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_PatchFHIRResource_Call) RunAndReturn(run func(ctx context.Context, resourceType string, resourceID string, payload interface{}, resource interface{}) error) *MockHapiFHIRImplementation_PatchFHIRResource_Call {
	_c.Call.Return(run)
	return _c
}

// PostFHIRBundle provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) PostFHIRBundle(ctx context.Context, payload interface{}, response interface{}) error {
	ret := _mock.Called(ctx, payload, response)

	if len(ret) == 0 {
		panic("no return value specified for PostFHIRBundle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}) error); ok {
		r0 = returnFunc(ctx, payload, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_PostFHIRBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostFHIRBundle'
type MockHapiFHIRImplementation_PostFHIRBundle_Call struct {
	*mock.Call
}

// PostFHIRBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - payload interface{}
//   - response interface{}
func (_e *MockHapiFHIRImplementation_Expecter) PostFHIRBundle(ctx interface{}, payload interface{}, response interface{}) *MockHapiFHIRImplementation_PostFHIRBundle_Call {
	return &MockHapiFHIRImplementation_PostFHIRBundle_Call{Call: _e.mock.On("PostFHIRBundle", ctx, payload, response)}
}

func (_c *MockHapiFHIRImplementation_PostFHIRBundle_Call) Run(run func(ctx context.Context, payload interface{}, response interface{})) *MockHapiFHIRImplementation_PostFHIRBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_PostFHIRBundle_Call) Return(err error) *MockHapiFHIRImplementation_PostFHIRBundle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_PostFHIRBundle_Call) RunAndReturn(run func(ctx context.Context, payload interface{}, response interface{}) error) *MockHapiFHIRImplementation_PostFHIRBundle_Call {
	_c.Call.Return(run)
	return _c
}

// PutFHIRResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) PutFHIRResource(ctx context.Context, resourceType string, resourceID string, payload map[string]any, resource any, useCREnabledServer bool) error {
	ret := _mock.Called(ctx, resourceType, resourceID, payload, resource, useCREnabledServer)

	if len(ret) == 0 {
		panic("no return value specified for PutFHIRResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any, any, bool) error); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, payload, resource, useCREnabledServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_PutFHIRResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutFHIRResource'
type MockHapiFHIRImplementation_PutFHIRResource_Call struct {
	*mock.Call
}

// PutFHIRResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - resourceID string
//   - payload map[string]any
//   - resource any
//   - useCREnabledServer bool
func (_e *MockHapiFHIRImplementation_Expecter) PutFHIRResource(ctx interface{}, resourceType interface{}, resourceID interface{}, payload interface{}, resource interface{}, useCREnabledServer interface{}) *MockHapiFHIRImplementation_PutFHIRResource_Call {
	return &MockHapiFHIRImplementation_PutFHIRResource_Call{Call: _e.mock.On("PutFHIRResource", ctx, resourceType, resourceID, payload, resource, useCREnabledServer)}
}

func (_c *MockHapiFHIRImplementation_PutFHIRResource_Call) Run(run func(ctx context.Context, resourceType string, resourceID string, payload map[string]any, resource any, useCREnabledServer bool)) *MockHapiFHIRImplementation_PutFHIRResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_PutFHIRResource_Call) Return(err error) *MockHapiFHIRImplementation_PutFHIRResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_PutFHIRResource_Call) RunAndReturn(run func(ctx context.Context, resourceType string, resourceID string, payload map[string]any, resource any, useCREnabledServer bool) error) *MockHapiFHIRImplementation_PutFHIRResource_Call {
	_c.Call.Return(run)
	return _c
}

// SearchFHIRResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) SearchFHIRResource(ctx context.Context, bundleID string, resourceType string, params map[string]any, tenant dto.TenantIdentifiers, bundle interface{}) error {
	ret := _mock.Called(ctx, bundleID, resourceType, params, tenant, bundle)

	if len(ret) == 0 {
		panic("no return value specified for SearchFHIRResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any, dto.TenantIdentifiers, interface{}) error); ok {
		r0 = returnFunc(ctx, bundleID, resourceType, params, tenant, bundle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_SearchFHIRResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFHIRResource'
type MockHapiFHIRImplementation_SearchFHIRResource_Call struct {
	*mock.Call
}

// SearchFHIRResource is a helper method to define mock.On call
//   - ctx context.Context
//   - bundleID string
//   - resourceType string
//   - params map[string]any
//   - tenant dto.TenantIdentifiers
//   - bundle interface{}
func (_e *MockHapiFHIRImplementation_Expecter) SearchFHIRResource(ctx interface{}, bundleID interface{}, resourceType interface{}, params interface{}, tenant interface{}, bundle interface{}) *MockHapiFHIRImplementation_SearchFHIRResource_Call {
	return &MockHapiFHIRImplementation_SearchFHIRResource_Call{Call: _e.mock.On("SearchFHIRResource", ctx, bundleID, resourceType, params, tenant, bundle)}
}

func (_c *MockHapiFHIRImplementation_SearchFHIRResource_Call) Run(run func(ctx context.Context, bundleID string, resourceType string, params map[string]any, tenant dto.TenantIdentifiers, bundle interface{})) *MockHapiFHIRImplementation_SearchFHIRResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		var arg4 dto.TenantIdentifiers
		if args[4] != nil {
			arg4 = args[4].(dto.TenantIdentifiers)
		}
		var arg5 interface{}
		if args[5] != nil {
			arg5 = args[5].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_SearchFHIRResource_Call) Return(err error) *MockHapiFHIRImplementation_SearchFHIRResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_SearchFHIRResource_Call) RunAndReturn(run func(ctx context.Context, bundleID string, resourceType string, params map[string]any, tenant dto.TenantIdentifiers, bundle interface{}) error) *MockHapiFHIRImplementation_SearchFHIRResource_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateResource provides a mock function for the type MockHapiFHIRImplementation
func (_mock *MockHapiFHIRImplementation) ValidateResource(ctx context.Context, resourceType string, params map[string]interface{}) error {
	ret := _mock.Called(ctx, resourceType, params)

	if len(ret) == 0 {
		panic("no return value specified for ValidateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, resourceType, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHapiFHIRImplementation_ValidateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateResource'
type MockHapiFHIRImplementation_ValidateResource_Call struct {
	*mock.Call
}

// ValidateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - params map[string]interface{}
func (_e *MockHapiFHIRImplementation_Expecter) ValidateResource(ctx interface{}, resourceType interface{}, params interface{}) *MockHapiFHIRImplementation_ValidateResource_Call {
	return &MockHapiFHIRImplementation_ValidateResource_Call{Call: _e.mock.On("ValidateResource", ctx, resourceType, params)}
}

func (_c *MockHapiFHIRImplementation_ValidateResource_Call) Run(run func(ctx context.Context, resourceType string, params map[string]interface{})) *MockHapiFHIRImplementation_ValidateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHapiFHIRImplementation_ValidateResource_Call) Return(err error) *MockHapiFHIRImplementation_ValidateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHapiFHIRImplementation_ValidateResource_Call) RunAndReturn(run func(ctx context.Context, resourceType string, params map[string]interface{}) error) *MockHapiFHIRImplementation_ValidateResource_Call {
	_c.Call.Return(run)
	return _c
}
