// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/savannahghi/silurlshortener"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIServiceURLShortener creates a new instance of MockIServiceURLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceURLShortener {
	mock := &MockIServiceURLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServiceURLShortener is an autogenerated mock type for the IServiceURLShortener type
type MockIServiceURLShortener struct {
	mock.Mock
}

type MockIServiceURLShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceURLShortener) EXPECT() *MockIServiceURLShortener_Expecter {
	return &MockIServiceURLShortener_Expecter{mock: &_m.Mock}
}

// Shorten provides a mock function for the type MockIServiceURLShortener
func (_mock *MockIServiceURLShortener) Shorten(ctx context.Context, payload *silurlshortener.ShortenURLPayload) (*silurlshortener.ShortenURLResponse, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 *silurlshortener.ShortenURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *silurlshortener.ShortenURLPayload) (*silurlshortener.ShortenURLResponse, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *silurlshortener.ShortenURLPayload) *silurlshortener.ShortenURLResponse); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*silurlshortener.ShortenURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *silurlshortener.ShortenURLPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServiceURLShortener_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockIServiceURLShortener_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *silurlshortener.ShortenURLPayload
func (_e *MockIServiceURLShortener_Expecter) Shorten(ctx interface{}, payload interface{}) *MockIServiceURLShortener_Shorten_Call {
	return &MockIServiceURLShortener_Shorten_Call{Call: _e.mock.On("Shorten", ctx, payload)}
}

func (_c *MockIServiceURLShortener_Shorten_Call) Run(run func(ctx context.Context, payload *silurlshortener.ShortenURLPayload)) *MockIServiceURLShortener_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *silurlshortener.ShortenURLPayload
		if args[1] != nil {
			arg1 = args[1].(*silurlshortener.ShortenURLPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceURLShortener_Shorten_Call) Return(shortenURLResponse *silurlshortener.ShortenURLResponse, err error) *MockIServiceURLShortener_Shorten_Call {
	_c.Call.Return(shortenURLResponse, err)
	return _c
}

func (_c *MockIServiceURLShortener_Shorten_Call) RunAndReturn(run func(ctx context.Context, payload *silurlshortener.ShortenURLPayload) (*silurlshortener.ShortenURLResponse, error)) *MockIServiceURLShortener_Shorten_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIURLShortenerClient creates a new instance of MockIURLShortenerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIURLShortenerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIURLShortenerClient {
	mock := &MockIURLShortenerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIURLShortenerClient is an autogenerated mock type for the IURLShortenerClient type
type MockIURLShortenerClient struct {
	mock.Mock
}

type MockIURLShortenerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIURLShortenerClient) EXPECT() *MockIURLShortenerClient_Expecter {
	return &MockIURLShortenerClient_Expecter{mock: &_m.Mock}
}

// ShortenURL provides a mock function for the type MockIURLShortenerClient
func (_mock *MockIURLShortenerClient) ShortenURL(ctx context.Context, payload *silurlshortener.ShortenURLPayload) (*silurlshortener.ShortenURLResponse, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 *silurlshortener.ShortenURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *silurlshortener.ShortenURLPayload) (*silurlshortener.ShortenURLResponse, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *silurlshortener.ShortenURLPayload) *silurlshortener.ShortenURLResponse); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*silurlshortener.ShortenURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *silurlshortener.ShortenURLPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIURLShortenerClient_ShortenURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenURL'
type MockIURLShortenerClient_ShortenURL_Call struct {
	*mock.Call
}

// ShortenURL is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *silurlshortener.ShortenURLPayload
func (_e *MockIURLShortenerClient_Expecter) ShortenURL(ctx interface{}, payload interface{}) *MockIURLShortenerClient_ShortenURL_Call {
	return &MockIURLShortenerClient_ShortenURL_Call{Call: _e.mock.On("ShortenURL", ctx, payload)}
}

func (_c *MockIURLShortenerClient_ShortenURL_Call) Run(run func(ctx context.Context, payload *silurlshortener.ShortenURLPayload)) *MockIURLShortenerClient_ShortenURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *silurlshortener.ShortenURLPayload
		if args[1] != nil {
			arg1 = args[1].(*silurlshortener.ShortenURLPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIURLShortenerClient_ShortenURL_Call) Return(shortenURLResponse *silurlshortener.ShortenURLResponse, err error) *MockIURLShortenerClient_ShortenURL_Call {
	_c.Call.Return(shortenURLResponse, err)
	return _c
}

func (_c *MockIURLShortenerClient_ShortenURL_Call) RunAndReturn(run func(ctx context.Context, payload *silurlshortener.ShortenURLPayload) (*silurlshortener.ShortenURLResponse, error)) *MockIURLShortenerClient_ShortenURL_Call {
	_c.Call.Return(run)
	return _c
}
