// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"io"
	"net/http"
	"net/url"

	"github.com/savannahghi/interserviceclient"
	"github.com/savannahghi/profileutils"
	"github.com/savannahghi/pubsubtools"
	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
	"github.com/savannahghi/empower-clinical/pkg/clinical/domain"
)

// NewMockServiceOCL creates a new instance of MockServiceOCL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceOCL(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceOCL {
	mock := &MockServiceOCL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceOCL is an autogenerated mock type for the ServiceOCL type
type MockServiceOCL struct {
	mock.Mock
}

type MockServiceOCL_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceOCL) EXPECT() *MockServiceOCL_Expecter {
	return &MockServiceOCL_Expecter{mock: &_m.Mock}
}

// GetConcept provides a mock function for the type MockServiceOCL
func (_mock *MockServiceOCL) GetConcept(ctx context.Context, org string, source string, concept string, includeMappings bool, includeInverseMappings bool) (*domain.Concept, error) {
	ret := _mock.Called(ctx, org, source, concept, includeMappings, includeInverseMappings)

	if len(ret) == 0 {
		panic("no return value specified for GetConcept")
	}

	var r0 *domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool, bool) (*domain.Concept, error)); ok {
		return returnFunc(ctx, org, source, concept, includeMappings, includeInverseMappings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool, bool) *domain.Concept); ok {
		r0 = returnFunc(ctx, org, source, concept, includeMappings, includeInverseMappings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Concept)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, bool, bool) error); ok {
		r1 = returnFunc(ctx, org, source, concept, includeMappings, includeInverseMappings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceOCL_GetConcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConcept'
type MockServiceOCL_GetConcept_Call struct {
	*mock.Call
}

// GetConcept is a helper method to define mock.On call
//   - ctx context.Context
//   - org string
//   - source string
//   - concept string
//   - includeMappings bool
//   - includeInverseMappings bool
func (_e *MockServiceOCL_Expecter) GetConcept(ctx interface{}, org interface{}, source interface{}, concept interface{}, includeMappings interface{}, includeInverseMappings interface{}) *MockServiceOCL_GetConcept_Call {
	return &MockServiceOCL_GetConcept_Call{Call: _e.mock.On("GetConcept", ctx, org, source, concept, includeMappings, includeInverseMappings)}
}

func (_c *MockServiceOCL_GetConcept_Call) Run(run func(ctx context.Context, org string, source string, concept string, includeMappings bool, includeInverseMappings bool)) *MockServiceOCL_GetConcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockServiceOCL_GetConcept_Call) Return(concept1 *domain.Concept, err error) *MockServiceOCL_GetConcept_Call {
	_c.Call.Return(concept1, err)
	return _c
}

func (_c *MockServiceOCL_GetConcept_Call) RunAndReturn(run func(ctx context.Context, org string, source string, concept string, includeMappings bool, includeInverseMappings bool) (*domain.Concept, error)) *MockServiceOCL_GetConcept_Call {
	_c.Call.Return(run)
	return _c
}

// ListConcepts provides a mock function for the type MockServiceOCL
func (_mock *MockServiceOCL) ListConcepts(ctx context.Context, org []string, source []string, verbose bool, q *string, sortAsc *string, sortDesc *string, conceptClass *string, dataType *string, locale *string, includeRetired *bool, includeMappings *bool, includeInverseMappings *bool, paginationInput *dto.Pagination) (*domain.ConceptPage, error) {
	ret := _mock.Called(ctx, org, source, verbose, q, sortAsc, sortDesc, conceptClass, dataType, locale, includeRetired, includeMappings, includeInverseMappings, paginationInput)

	if len(ret) == 0 {
		panic("no return value specified for ListConcepts")
	}

	var r0 *domain.ConceptPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string, bool, *string, *string, *string, *string, *string, *string, *bool, *bool, *bool, *dto.Pagination) (*domain.ConceptPage, error)); ok {
		return returnFunc(ctx, org, source, verbose, q, sortAsc, sortDesc, conceptClass, dataType, locale, includeRetired, includeMappings, includeInverseMappings, paginationInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string, bool, *string, *string, *string, *string, *string, *string, *bool, *bool, *bool, *dto.Pagination) *domain.ConceptPage); ok {
		r0 = returnFunc(ctx, org, source, verbose, q, sortAsc, sortDesc, conceptClass, dataType, locale, includeRetired, includeMappings, includeInverseMappings, paginationInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ConceptPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []string, bool, *string, *string, *string, *string, *string, *string, *bool, *bool, *bool, *dto.Pagination) error); ok {
		r1 = returnFunc(ctx, org, source, verbose, q, sortAsc, sortDesc, conceptClass, dataType, locale, includeRetired, includeMappings, includeInverseMappings, paginationInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceOCL_ListConcepts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConcepts'
type MockServiceOCL_ListConcepts_Call struct {
	*mock.Call
}

// ListConcepts is a helper method to define mock.On call
//   - ctx context.Context
//   - org []string
//   - source []string
//   - verbose bool
//   - q *string
//   - sortAsc *string
//   - sortDesc *string
//   - conceptClass *string
//   - dataType *string
//   - locale *string
//   - includeRetired *bool
//   - includeMappings *bool
//   - includeInverseMappings *bool
//   - paginationInput *dto.Pagination
func (_e *MockServiceOCL_Expecter) ListConcepts(ctx interface{}, org interface{}, source interface{}, verbose interface{}, q interface{}, sortAsc interface{}, sortDesc interface{}, conceptClass interface{}, dataType interface{}, locale interface{}, includeRetired interface{}, includeMappings interface{}, includeInverseMappings interface{}, paginationInput interface{}) *MockServiceOCL_ListConcepts_Call {
	return &MockServiceOCL_ListConcepts_Call{Call: _e.mock.On("ListConcepts", ctx, org, source, verbose, q, sortAsc, sortDesc, conceptClass, dataType, locale, includeRetired, includeMappings, includeInverseMappings, paginationInput)}
}

func (_c *MockServiceOCL_ListConcepts_Call) Run(run func(ctx context.Context, org []string, source []string, verbose bool, q *string, sortAsc *string, sortDesc *string, conceptClass *string, dataType *string, locale *string, includeRetired *bool, includeMappings *bool, includeInverseMappings *bool, paginationInput *dto.Pagination)) *MockServiceOCL_ListConcepts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		var arg6 *string
		if args[6] != nil {
			arg6 = args[6].(*string)
		}
		var arg7 *string
		if args[7] != nil {
			arg7 = args[7].(*string)
		}
		var arg8 *string
		if args[8] != nil {
			arg8 = args[8].(*string)
		}
		var arg9 *string
		if args[9] != nil {
			arg9 = args[9].(*string)
		}
		var arg10 *bool
		if args[10] != nil {
			arg10 = args[10].(*bool)
		}
		var arg11 *bool
		if args[11] != nil {
			arg11 = args[11].(*bool)
		}
		var arg12 *bool
		if args[12] != nil {
			arg12 = args[12].(*bool)
		}
		var arg13 *dto.Pagination
		if args[13] != nil {
			arg13 = args[13].(*dto.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
			arg11,
			arg12,
			arg13,
		)
	})
	return _c
}

func (_c *MockServiceOCL_ListConcepts_Call) Return(conceptPage *domain.ConceptPage, err error) *MockServiceOCL_ListConcepts_Call {
	_c.Call.Return(conceptPage, err)
	return _c
}

func (_c *MockServiceOCL_ListConcepts_Call) RunAndReturn(run func(ctx context.Context, org []string, source []string, verbose bool, q *string, sortAsc *string, sortDesc *string, conceptClass *string, dataType *string, locale *string, includeRetired *bool, includeMappings *bool, includeInverseMappings *bool, paginationInput *dto.Pagination) (*domain.ConceptPage, error)) *MockServiceOCL_ListConcepts_Call {
	_c.Call.Return(run)
	return _c
}

// MakeRequest provides a mock function for the type MockServiceOCL
func (_mock *MockServiceOCL) MakeRequest(method string, path string, params url.Values, body io.Reader) (*http.Response, error) {
	ret := _mock.Called(method, path, params, body)

	if len(ret) == 0 {
		panic("no return value specified for MakeRequest")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, url.Values, io.Reader) (*http.Response, error)); ok {
		return returnFunc(method, path, params, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, url.Values, io.Reader) *http.Response); ok {
		r0 = returnFunc(method, path, params, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, url.Values, io.Reader) error); ok {
		r1 = returnFunc(method, path, params, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceOCL_MakeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRequest'
type MockServiceOCL_MakeRequest_Call struct {
	*mock.Call
}

// MakeRequest is a helper method to define mock.On call
//   - method string
//   - path string
//   - params url.Values
//   - body io.Reader
func (_e *MockServiceOCL_Expecter) MakeRequest(method interface{}, path interface{}, params interface{}, body interface{}) *MockServiceOCL_MakeRequest_Call {
	return &MockServiceOCL_MakeRequest_Call{Call: _e.mock.On("MakeRequest", method, path, params, body)}
}

func (_c *MockServiceOCL_MakeRequest_Call) Run(run func(method string, path string, params url.Values, body io.Reader)) *MockServiceOCL_MakeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 url.Values
		if args[2] != nil {
			arg2 = args[2].(url.Values)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceOCL_MakeRequest_Call) Return(response *http.Response, err error) *MockServiceOCL_MakeRequest_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockServiceOCL_MakeRequest_Call) RunAndReturn(run func(method string, path string, params url.Values, body io.Reader) (*http.Response, error)) *MockServiceOCL_MakeRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBaseExtension creates a new instance of MockBaseExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseExtension {
	mock := &MockBaseExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseExtension is an autogenerated mock type for the BaseExtension type
type MockBaseExtension struct {
	mock.Mock
}

type MockBaseExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBaseExtension) EXPECT() *MockBaseExtension_Expecter {
	return &MockBaseExtension_Expecter{mock: &_m.Mock}
}

// ErrorMap provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) ErrorMap(err error) map[string]string {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for ErrorMap")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func(error) map[string]string); ok {
		r0 = returnFunc(err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockBaseExtension_ErrorMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorMap'
type MockBaseExtension_ErrorMap_Call struct {
	*mock.Call
}

// ErrorMap is a helper method to define mock.On call
//   - err error
func (_e *MockBaseExtension_Expecter) ErrorMap(err interface{}) *MockBaseExtension_ErrorMap_Call {
	return &MockBaseExtension_ErrorMap_Call{Call: _e.mock.On("ErrorMap", err)}
}

func (_c *MockBaseExtension_ErrorMap_Call) Run(run func(err error)) *MockBaseExtension_ErrorMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_ErrorMap_Call) Return(stringToString map[string]string) *MockBaseExtension_ErrorMap_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockBaseExtension_ErrorMap_Call) RunAndReturn(run func(err error) map[string]string) *MockBaseExtension_ErrorMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvVar provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) GetEnvVar(envName string) (string, error) {
	ret := _mock.Called(envName)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvVar")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(envName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(envName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(envName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_GetEnvVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvVar'
type MockBaseExtension_GetEnvVar_Call struct {
	*mock.Call
}

// GetEnvVar is a helper method to define mock.On call
//   - envName string
func (_e *MockBaseExtension_Expecter) GetEnvVar(envName interface{}) *MockBaseExtension_GetEnvVar_Call {
	return &MockBaseExtension_GetEnvVar_Call{Call: _e.mock.On("GetEnvVar", envName)}
}

func (_c *MockBaseExtension_GetEnvVar_Call) Run(run func(envName string)) *MockBaseExtension_GetEnvVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_GetEnvVar_Call) Return(s string, err error) *MockBaseExtension_GetEnvVar_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBaseExtension_GetEnvVar_Call) RunAndReturn(run func(envName string) (string, error)) *MockBaseExtension_GetEnvVar_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoggedInUser provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) GetLoggedInUser(ctx context.Context) (*profileutils.UserInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLoggedInUser")
	}

	var r0 *profileutils.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*profileutils.UserInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *profileutils.UserInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profileutils.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_GetLoggedInUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoggedInUser'
type MockBaseExtension_GetLoggedInUser_Call struct {
	*mock.Call
}

// GetLoggedInUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBaseExtension_Expecter) GetLoggedInUser(ctx interface{}) *MockBaseExtension_GetLoggedInUser_Call {
	return &MockBaseExtension_GetLoggedInUser_Call{Call: _e.mock.On("GetLoggedInUser", ctx)}
}

func (_c *MockBaseExtension_GetLoggedInUser_Call) Run(run func(ctx context.Context)) *MockBaseExtension_GetLoggedInUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_GetLoggedInUser_Call) Return(userInfo *profileutils.UserInfo, err error) *MockBaseExtension_GetLoggedInUser_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockBaseExtension_GetLoggedInUser_Call) RunAndReturn(run func(ctx context.Context) (*profileutils.UserInfo, error)) *MockBaseExtension_GetLoggedInUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoggedInUserUID provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) GetLoggedInUserUID(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLoggedInUserUID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_GetLoggedInUserUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoggedInUserUID'
type MockBaseExtension_GetLoggedInUserUID_Call struct {
	*mock.Call
}

// GetLoggedInUserUID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBaseExtension_Expecter) GetLoggedInUserUID(ctx interface{}) *MockBaseExtension_GetLoggedInUserUID_Call {
	return &MockBaseExtension_GetLoggedInUserUID_Call{Call: _e.mock.On("GetLoggedInUserUID", ctx)}
}

func (_c *MockBaseExtension_GetLoggedInUserUID_Call) Run(run func(ctx context.Context)) *MockBaseExtension_GetLoggedInUserUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_GetLoggedInUserUID_Call) Return(s string, err error) *MockBaseExtension_GetLoggedInUserUID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBaseExtension_GetLoggedInUserUID_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockBaseExtension_GetLoggedInUserUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPubSubTopic provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) GetPubSubTopic(m *pubsubtools.PubSubPayload) (string, error) {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for GetPubSubTopic")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*pubsubtools.PubSubPayload) (string, error)); ok {
		return returnFunc(m)
	}
	if returnFunc, ok := ret.Get(0).(func(*pubsubtools.PubSubPayload) string); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*pubsubtools.PubSubPayload) error); ok {
		r1 = returnFunc(m)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_GetPubSubTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPubSubTopic'
type MockBaseExtension_GetPubSubTopic_Call struct {
	*mock.Call
}

// GetPubSubTopic is a helper method to define mock.On call
//   - m *pubsubtools.PubSubPayload
func (_e *MockBaseExtension_Expecter) GetPubSubTopic(m interface{}) *MockBaseExtension_GetPubSubTopic_Call {
	return &MockBaseExtension_GetPubSubTopic_Call{Call: _e.mock.On("GetPubSubTopic", m)}
}

func (_c *MockBaseExtension_GetPubSubTopic_Call) Run(run func(m *pubsubtools.PubSubPayload)) *MockBaseExtension_GetPubSubTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pubsubtools.PubSubPayload
		if args[0] != nil {
			arg0 = args[0].(*pubsubtools.PubSubPayload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_GetPubSubTopic_Call) Return(s string, err error) *MockBaseExtension_GetPubSubTopic_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBaseExtension_GetPubSubTopic_Call) RunAndReturn(run func(m *pubsubtools.PubSubPayload) (string, error)) *MockBaseExtension_GetPubSubTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantIdentifiers provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) GetTenantIdentifiers(ctx context.Context) (*dto.TenantIdentifiers, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantIdentifiers")
	}

	var r0 *dto.TenantIdentifiers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*dto.TenantIdentifiers, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *dto.TenantIdentifiers); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TenantIdentifiers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_GetTenantIdentifiers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantIdentifiers'
type MockBaseExtension_GetTenantIdentifiers_Call struct {
	*mock.Call
}

// GetTenantIdentifiers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBaseExtension_Expecter) GetTenantIdentifiers(ctx interface{}) *MockBaseExtension_GetTenantIdentifiers_Call {
	return &MockBaseExtension_GetTenantIdentifiers_Call{Call: _e.mock.On("GetTenantIdentifiers", ctx)}
}

func (_c *MockBaseExtension_GetTenantIdentifiers_Call) Run(run func(ctx context.Context)) *MockBaseExtension_GetTenantIdentifiers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_GetTenantIdentifiers_Call) Return(tenantIdentifiers *dto.TenantIdentifiers, err error) *MockBaseExtension_GetTenantIdentifiers_Call {
	_c.Call.Return(tenantIdentifiers, err)
	return _c
}

func (_c *MockBaseExtension_GetTenantIdentifiers_Call) RunAndReturn(run func(ctx context.Context) (*dto.TenantIdentifiers, error)) *MockBaseExtension_GetTenantIdentifiers_Call {
	_c.Call.Return(run)
	return _c
}

// LoadDepsFromYAML provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) LoadDepsFromYAML() (*interserviceclient.DepsConfig, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadDepsFromYAML")
	}

	var r0 *interserviceclient.DepsConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*interserviceclient.DepsConfig, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *interserviceclient.DepsConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interserviceclient.DepsConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_LoadDepsFromYAML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadDepsFromYAML'
type MockBaseExtension_LoadDepsFromYAML_Call struct {
	*mock.Call
}

// LoadDepsFromYAML is a helper method to define mock.On call
func (_e *MockBaseExtension_Expecter) LoadDepsFromYAML() *MockBaseExtension_LoadDepsFromYAML_Call {
	return &MockBaseExtension_LoadDepsFromYAML_Call{Call: _e.mock.On("LoadDepsFromYAML")}
}

func (_c *MockBaseExtension_LoadDepsFromYAML_Call) Run(run func()) *MockBaseExtension_LoadDepsFromYAML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBaseExtension_LoadDepsFromYAML_Call) Return(depsConfig *interserviceclient.DepsConfig, err error) *MockBaseExtension_LoadDepsFromYAML_Call {
	_c.Call.Return(depsConfig, err)
	return _c
}

func (_c *MockBaseExtension_LoadDepsFromYAML_Call) RunAndReturn(run func() (*interserviceclient.DepsConfig, error)) *MockBaseExtension_LoadDepsFromYAML_Call {
	_c.Call.Return(run)
	return _c
}

// NormalizeMSISDN provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) NormalizeMSISDN(msisdn string) (*string, error) {
	ret := _mock.Called(msisdn)

	if len(ret) == 0 {
		panic("no return value specified for NormalizeMSISDN")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*string, error)); ok {
		return returnFunc(msisdn)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *string); ok {
		r0 = returnFunc(msisdn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(msisdn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_NormalizeMSISDN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NormalizeMSISDN'
type MockBaseExtension_NormalizeMSISDN_Call struct {
	*mock.Call
}

// NormalizeMSISDN is a helper method to define mock.On call
//   - msisdn string
func (_e *MockBaseExtension_Expecter) NormalizeMSISDN(msisdn interface{}) *MockBaseExtension_NormalizeMSISDN_Call {
	return &MockBaseExtension_NormalizeMSISDN_Call{Call: _e.mock.On("NormalizeMSISDN", msisdn)}
}

func (_c *MockBaseExtension_NormalizeMSISDN_Call) Run(run func(msisdn string)) *MockBaseExtension_NormalizeMSISDN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseExtension_NormalizeMSISDN_Call) Return(s *string, err error) *MockBaseExtension_NormalizeMSISDN_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBaseExtension_NormalizeMSISDN_Call) RunAndReturn(run func(msisdn string) (*string, error)) *MockBaseExtension_NormalizeMSISDN_Call {
	_c.Call.Return(run)
	return _c
}

// SetupISCclient provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) SetupISCclient(config interserviceclient.DepsConfig, serviceName string) (*interserviceclient.InterServiceClient, error) {
	ret := _mock.Called(config, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for SetupISCclient")
	}

	var r0 *interserviceclient.InterServiceClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interserviceclient.DepsConfig, string) (*interserviceclient.InterServiceClient, error)); ok {
		return returnFunc(config, serviceName)
	}
	if returnFunc, ok := ret.Get(0).(func(interserviceclient.DepsConfig, string) *interserviceclient.InterServiceClient); ok {
		r0 = returnFunc(config, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interserviceclient.InterServiceClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interserviceclient.DepsConfig, string) error); ok {
		r1 = returnFunc(config, serviceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_SetupISCclient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupISCclient'
type MockBaseExtension_SetupISCclient_Call struct {
	*mock.Call
}

// SetupISCclient is a helper method to define mock.On call
//   - config interserviceclient.DepsConfig
//   - serviceName string
func (_e *MockBaseExtension_Expecter) SetupISCclient(config interface{}, serviceName interface{}) *MockBaseExtension_SetupISCclient_Call {
	return &MockBaseExtension_SetupISCclient_Call{Call: _e.mock.On("SetupISCclient", config, serviceName)}
}

func (_c *MockBaseExtension_SetupISCclient_Call) Run(run func(config interserviceclient.DepsConfig, serviceName string)) *MockBaseExtension_SetupISCclient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interserviceclient.DepsConfig
		if args[0] != nil {
			arg0 = args[0].(interserviceclient.DepsConfig)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseExtension_SetupISCclient_Call) Return(interServiceClient *interserviceclient.InterServiceClient, err error) *MockBaseExtension_SetupISCclient_Call {
	_c.Call.Return(interServiceClient, err)
	return _c
}

func (_c *MockBaseExtension_SetupISCclient_Call) RunAndReturn(run func(config interserviceclient.DepsConfig, serviceName string) (*interserviceclient.InterServiceClient, error)) *MockBaseExtension_SetupISCclient_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPubSubJWTAndDecodePayload provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) VerifyPubSubJWTAndDecodePayload(w http.ResponseWriter, r *http.Request) (*pubsubtools.PubSubPayload, error) {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPubSubJWTAndDecodePayload")
	}

	var r0 *pubsubtools.PubSubPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) (*pubsubtools.PubSubPayload, error)); ok {
		return returnFunc(w, r)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) *pubsubtools.PubSubPayload); ok {
		r0 = returnFunc(w, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsubtools.PubSubPayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) error); ok {
		r1 = returnFunc(w, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPubSubJWTAndDecodePayload'
type MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call struct {
	*mock.Call
}

// VerifyPubSubJWTAndDecodePayload is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockBaseExtension_Expecter) VerifyPubSubJWTAndDecodePayload(w interface{}, r interface{}) *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call {
	return &MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call{Call: _e.mock.On("VerifyPubSubJWTAndDecodePayload", w, r)}
}

func (_c *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call) Return(pubSubPayload *pubsubtools.PubSubPayload, err error) *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call {
	_c.Call.Return(pubSubPayload, err)
	return _c
}

func (_c *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) (*pubsubtools.PubSubPayload, error)) *MockBaseExtension_VerifyPubSubJWTAndDecodePayload_Call {
	_c.Call.Return(run)
	return _c
}

// WriteJSONResponse provides a mock function for the type MockBaseExtension
func (_mock *MockBaseExtension) WriteJSONResponse(w http.ResponseWriter, source interface{}, status int) {
	_mock.Called(w, source, status)
	return
}

// MockBaseExtension_WriteJSONResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteJSONResponse'
type MockBaseExtension_WriteJSONResponse_Call struct {
	*mock.Call
}

// WriteJSONResponse is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - source interface{}
//   - status int
func (_e *MockBaseExtension_Expecter) WriteJSONResponse(w interface{}, source interface{}, status interface{}) *MockBaseExtension_WriteJSONResponse_Call {
	return &MockBaseExtension_WriteJSONResponse_Call{Call: _e.mock.On("WriteJSONResponse", w, source, status)}
}

func (_c *MockBaseExtension_WriteJSONResponse_Call) Run(run func(w http.ResponseWriter, source interface{}, status int)) *MockBaseExtension_WriteJSONResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBaseExtension_WriteJSONResponse_Call) Return() *MockBaseExtension_WriteJSONResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBaseExtension_WriteJSONResponse_Call) RunAndReturn(run func(w http.ResponseWriter, source interface{}, status int)) *MockBaseExtension_WriteJSONResponse_Call {
	_c.Run(run)
	return _c
}
