// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/Nerzal/gocloak/v13"
	mock "github.com/stretchr/testify/mock"
)

// NewMockgocloaker creates a new instance of Mockgocloaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockgocloaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockgocloaker {
	mock := &Mockgocloaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockgocloaker is an autogenerated mock type for the gocloaker type
type Mockgocloaker struct {
	mock.Mock
}

type Mockgocloaker_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockgocloaker) EXPECT() *Mockgocloaker_Expecter {
	return &Mockgocloaker_Expecter{mock: &_m.Mock}
}

// RetrospectToken provides a mock function for the type Mockgocloaker
func (_mock *Mockgocloaker) RetrospectToken(ctx context.Context, accessToken string, clientID string, clientSecret string, realm string) (*gocloak.IntroSpectTokenResult, error) {
	ret := _mock.Called(ctx, accessToken, clientID, clientSecret, realm)

	if len(ret) == 0 {
		panic("no return value specified for RetrospectToken")
	}

	var r0 *gocloak.IntroSpectTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*gocloak.IntroSpectTokenResult, error)); ok {
		return returnFunc(ctx, accessToken, clientID, clientSecret, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *gocloak.IntroSpectTokenResult); ok {
		r0 = returnFunc(ctx, accessToken, clientID, clientSecret, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.IntroSpectTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, accessToken, clientID, clientSecret, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockgocloaker_RetrospectToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrospectToken'
type Mockgocloaker_RetrospectToken_Call struct {
	*mock.Call
}

// RetrospectToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - clientID string
//   - clientSecret string
//   - realm string
func (_e *Mockgocloaker_Expecter) RetrospectToken(ctx interface{}, accessToken interface{}, clientID interface{}, clientSecret interface{}, realm interface{}) *Mockgocloaker_RetrospectToken_Call {
	return &Mockgocloaker_RetrospectToken_Call{Call: _e.mock.On("RetrospectToken", ctx, accessToken, clientID, clientSecret, realm)}
}

func (_c *Mockgocloaker_RetrospectToken_Call) Run(run func(ctx context.Context, accessToken string, clientID string, clientSecret string, realm string)) *Mockgocloaker_RetrospectToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Mockgocloaker_RetrospectToken_Call) Return(introSpectTokenResult *gocloak.IntroSpectTokenResult, err error) *Mockgocloaker_RetrospectToken_Call {
	_c.Call.Return(introSpectTokenResult, err)
	return _c
}

func (_c *Mockgocloaker_RetrospectToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string, clientID string, clientSecret string, realm string) (*gocloak.IntroSpectTokenResult, error)) *Mockgocloaker_RetrospectToken_Call {
	_c.Call.Return(run)
	return _c
}
