// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
)

// NewMockServiceUpload creates a new instance of MockServiceUpload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceUpload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceUpload {
	mock := &MockServiceUpload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceUpload is an autogenerated mock type for the ServiceUpload type
type MockServiceUpload struct {
	mock.Mock
}

type MockServiceUpload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceUpload) EXPECT() *MockServiceUpload_Expecter {
	return &MockServiceUpload_Expecter{mock: &_m.Mock}
}

// UploadMedia provides a mock function for the type MockServiceUpload
func (_mock *MockServiceUpload) UploadMedia(ctx context.Context, name string, file io.Reader, contentType string) (*dto.Media, error) {
	ret := _mock.Called(ctx, name, file, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 *dto.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) (*dto.Media, error)); ok {
		return returnFunc(ctx, name, file, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) *dto.Media); ok {
		r0 = returnFunc(ctx, name, file, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, string) error); ok {
		r1 = returnFunc(ctx, name, file, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceUpload_UploadMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMedia'
type MockServiceUpload_UploadMedia_Call struct {
	*mock.Call
}

// UploadMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - file io.Reader
//   - contentType string
func (_e *MockServiceUpload_Expecter) UploadMedia(ctx interface{}, name interface{}, file interface{}, contentType interface{}) *MockServiceUpload_UploadMedia_Call {
	return &MockServiceUpload_UploadMedia_Call{Call: _e.mock.On("UploadMedia", ctx, name, file, contentType)}
}

func (_c *MockServiceUpload_UploadMedia_Call) Run(run func(ctx context.Context, name string, file io.Reader, contentType string)) *MockServiceUpload_UploadMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceUpload_UploadMedia_Call) Return(media *dto.Media, err error) *MockServiceUpload_UploadMedia_Call {
	_c.Call.Return(media, err)
	return _c
}

func (_c *MockServiceUpload_UploadMedia_Call) RunAndReturn(run func(ctx context.Context, name string, file io.Reader, contentType string) (*dto.Media, error)) *MockServiceUpload_UploadMedia_Call {
	_c.Call.Return(run)
	return _c
}
