// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
	"github.com/savannahghi/empower-clinical/pkg/clinical/domain"
)

// NewMockServicePubsub creates a new instance of MockServicePubsub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicePubsub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicePubsub {
	mock := &MockServicePubsub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServicePubsub is an autogenerated mock type for the ServicePubsub type
type MockServicePubsub struct {
	mock.Mock
}

type MockServicePubsub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicePubsub) EXPECT() *MockServicePubsub_Expecter {
	return &MockServicePubsub_Expecter{mock: &_m.Mock}
}

// NotifyCreateFollowUpTask provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifyCreateFollowUpTask(ctx context.Context, data *domain.FHIRTaskInput) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyCreateFollowUpTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FHIRTaskInput) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifyCreateFollowUpTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyCreateFollowUpTask'
type MockServicePubsub_NotifyCreateFollowUpTask_Call struct {
	*mock.Call
}

// NotifyCreateFollowUpTask is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.FHIRTaskInput
func (_e *MockServicePubsub_Expecter) NotifyCreateFollowUpTask(ctx interface{}, data interface{}) *MockServicePubsub_NotifyCreateFollowUpTask_Call {
	return &MockServicePubsub_NotifyCreateFollowUpTask_Call{Call: _e.mock.On("NotifyCreateFollowUpTask", ctx, data)}
}

func (_c *MockServicePubsub_NotifyCreateFollowUpTask_Call) Run(run func(ctx context.Context, data *domain.FHIRTaskInput)) *MockServicePubsub_NotifyCreateFollowUpTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FHIRTaskInput
		if args[1] != nil {
			arg1 = args[1].(*domain.FHIRTaskInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifyCreateFollowUpTask_Call) Return(err error) *MockServicePubsub_NotifyCreateFollowUpTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifyCreateFollowUpTask_Call) RunAndReturn(run func(ctx context.Context, data *domain.FHIRTaskInput) error) *MockServicePubsub_NotifyCreateFollowUpTask_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyCreatePatientCarePlan provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifyCreatePatientCarePlan(ctx context.Context, data dto.CarePlanPayload) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyCreatePatientCarePlan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CarePlanPayload) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifyCreatePatientCarePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyCreatePatientCarePlan'
type MockServicePubsub_NotifyCreatePatientCarePlan_Call struct {
	*mock.Call
}

// NotifyCreatePatientCarePlan is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.CarePlanPayload
func (_e *MockServicePubsub_Expecter) NotifyCreatePatientCarePlan(ctx interface{}, data interface{}) *MockServicePubsub_NotifyCreatePatientCarePlan_Call {
	return &MockServicePubsub_NotifyCreatePatientCarePlan_Call{Call: _e.mock.On("NotifyCreatePatientCarePlan", ctx, data)}
}

func (_c *MockServicePubsub_NotifyCreatePatientCarePlan_Call) Run(run func(ctx context.Context, data dto.CarePlanPayload)) *MockServicePubsub_NotifyCreatePatientCarePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CarePlanPayload
		if args[1] != nil {
			arg1 = args[1].(dto.CarePlanPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifyCreatePatientCarePlan_Call) Return(err error) *MockServicePubsub_NotifyCreatePatientCarePlan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifyCreatePatientCarePlan_Call) RunAndReturn(run func(ctx context.Context, data dto.CarePlanPayload) error) *MockServicePubsub_NotifyCreatePatientCarePlan_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyCreatePatientReferralTask provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifyCreatePatientReferralTask(ctx context.Context, data dto.PatientReferralTaskPayload) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyCreatePatientReferralTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PatientReferralTaskPayload) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifyCreatePatientReferralTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyCreatePatientReferralTask'
type MockServicePubsub_NotifyCreatePatientReferralTask_Call struct {
	*mock.Call
}

// NotifyCreatePatientReferralTask is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.PatientReferralTaskPayload
func (_e *MockServicePubsub_Expecter) NotifyCreatePatientReferralTask(ctx interface{}, data interface{}) *MockServicePubsub_NotifyCreatePatientReferralTask_Call {
	return &MockServicePubsub_NotifyCreatePatientReferralTask_Call{Call: _e.mock.On("NotifyCreatePatientReferralTask", ctx, data)}
}

func (_c *MockServicePubsub_NotifyCreatePatientReferralTask_Call) Run(run func(ctx context.Context, data dto.PatientReferralTaskPayload)) *MockServicePubsub_NotifyCreatePatientReferralTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.PatientReferralTaskPayload
		if args[1] != nil {
			arg1 = args[1].(dto.PatientReferralTaskPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifyCreatePatientReferralTask_Call) Return(err error) *MockServicePubsub_NotifyCreatePatientReferralTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifyCreatePatientReferralTask_Call) RunAndReturn(run func(ctx context.Context, data dto.PatientReferralTaskPayload) error) *MockServicePubsub_NotifyCreatePatientReferralTask_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyFacilityFHIRIDUpdate provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifyFacilityFHIRIDUpdate(ctx context.Context, data dto.UpdateFacilityFHIRID) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyFacilityFHIRIDUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateFacilityFHIRID) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyFacilityFHIRIDUpdate'
type MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call struct {
	*mock.Call
}

// NotifyFacilityFHIRIDUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.UpdateFacilityFHIRID
func (_e *MockServicePubsub_Expecter) NotifyFacilityFHIRIDUpdate(ctx interface{}, data interface{}) *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call {
	return &MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call{Call: _e.mock.On("NotifyFacilityFHIRIDUpdate", ctx, data)}
}

func (_c *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call) Run(run func(ctx context.Context, data dto.UpdateFacilityFHIRID)) *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UpdateFacilityFHIRID
		if args[1] != nil {
			arg1 = args[1].(dto.UpdateFacilityFHIRID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call) Return(err error) *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call) RunAndReturn(run func(ctx context.Context, data dto.UpdateFacilityFHIRID) error) *MockServicePubsub_NotifyFacilityFHIRIDUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyPatientFHIRIDUpdate provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifyPatientFHIRIDUpdate(ctx context.Context, data dto.UpdatePatientFHIRID) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPatientFHIRIDUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdatePatientFHIRID) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifyPatientFHIRIDUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyPatientFHIRIDUpdate'
type MockServicePubsub_NotifyPatientFHIRIDUpdate_Call struct {
	*mock.Call
}

// NotifyPatientFHIRIDUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.UpdatePatientFHIRID
func (_e *MockServicePubsub_Expecter) NotifyPatientFHIRIDUpdate(ctx interface{}, data interface{}) *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call {
	return &MockServicePubsub_NotifyPatientFHIRIDUpdate_Call{Call: _e.mock.On("NotifyPatientFHIRIDUpdate", ctx, data)}
}

func (_c *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call) Run(run func(ctx context.Context, data dto.UpdatePatientFHIRID)) *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UpdatePatientFHIRID
		if args[1] != nil {
			arg1 = args[1].(dto.UpdatePatientFHIRID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call) Return(err error) *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call) RunAndReturn(run func(ctx context.Context, data dto.UpdatePatientFHIRID) error) *MockServicePubsub_NotifyPatientFHIRIDUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyProgramFHIRIDUpdate provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifyProgramFHIRIDUpdate(ctx context.Context, data dto.UpdateProgramFHIRID) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyProgramFHIRIDUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateProgramFHIRID) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifyProgramFHIRIDUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyProgramFHIRIDUpdate'
type MockServicePubsub_NotifyProgramFHIRIDUpdate_Call struct {
	*mock.Call
}

// NotifyProgramFHIRIDUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.UpdateProgramFHIRID
func (_e *MockServicePubsub_Expecter) NotifyProgramFHIRIDUpdate(ctx interface{}, data interface{}) *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call {
	return &MockServicePubsub_NotifyProgramFHIRIDUpdate_Call{Call: _e.mock.On("NotifyProgramFHIRIDUpdate", ctx, data)}
}

func (_c *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call) Run(run func(ctx context.Context, data dto.UpdateProgramFHIRID)) *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UpdateProgramFHIRID
		if args[1] != nil {
			arg1 = args[1].(dto.UpdateProgramFHIRID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call) Return(err error) *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call) RunAndReturn(run func(ctx context.Context, data dto.UpdateProgramFHIRID) error) *MockServicePubsub_NotifyProgramFHIRIDUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NotifySegmentation provides a mock function for the type MockServicePubsub
func (_mock *MockServicePubsub) NotifySegmentation(ctx context.Context, data dto.SegmentationPayload) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifySegmentation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SegmentationPayload) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServicePubsub_NotifySegmentation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifySegmentation'
type MockServicePubsub_NotifySegmentation_Call struct {
	*mock.Call
}

// NotifySegmentation is a helper method to define mock.On call
//   - ctx context.Context
//   - data dto.SegmentationPayload
func (_e *MockServicePubsub_Expecter) NotifySegmentation(ctx interface{}, data interface{}) *MockServicePubsub_NotifySegmentation_Call {
	return &MockServicePubsub_NotifySegmentation_Call{Call: _e.mock.On("NotifySegmentation", ctx, data)}
}

func (_c *MockServicePubsub_NotifySegmentation_Call) Run(run func(ctx context.Context, data dto.SegmentationPayload)) *MockServicePubsub_NotifySegmentation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.SegmentationPayload
		if args[1] != nil {
			arg1 = args[1].(dto.SegmentationPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServicePubsub_NotifySegmentation_Call) Return(err error) *MockServicePubsub_NotifySegmentation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServicePubsub_NotifySegmentation_Call) RunAndReturn(run func(ctx context.Context, data dto.SegmentationPayload) error) *MockServicePubsub_NotifySegmentation_Call {
	_c.Call.Return(run)
	return _c
}
