// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ses"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailSender creates a new instance of MockMailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailSender {
	mock := &MockMailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailSender is an autogenerated mock type for the MailSender type
type MockMailSender struct {
	mock.Mock
}

type MockMailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailSender) EXPECT() *MockMailSender_Expecter {
	return &MockMailSender_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type MockMailSender
func (_mock *MockMailSender) SendEmail(ctx context.Context, params *ses.SendEmailInput, optFns ...func(*ses.Options)) (*ses.SendEmailOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 *ses.SendEmailOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ses.SendEmailInput, ...func(*ses.Options)) (*ses.SendEmailOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ses.SendEmailInput, ...func(*ses.Options)) *ses.SendEmailOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ses.SendEmailOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ses.SendEmailInput, ...func(*ses.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMailSender_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockMailSender_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ses.SendEmailInput
//   - optFns ...func(*ses.Options)
func (_e *MockMailSender_Expecter) SendEmail(ctx interface{}, params interface{}, optFns ...interface{}) *MockMailSender_SendEmail_Call {
	return &MockMailSender_SendEmail_Call{Call: _e.mock.On("SendEmail",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockMailSender_SendEmail_Call) Run(run func(ctx context.Context, params *ses.SendEmailInput, optFns ...func(*ses.Options))) *MockMailSender_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ses.SendEmailInput
		if args[1] != nil {
			arg1 = args[1].(*ses.SendEmailInput)
		}
		var arg2 []func(*ses.Options)
		var variadicArgs []func(*ses.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ses.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMailSender_SendEmail_Call) Return(sendEmailOutput *ses.SendEmailOutput, err error) *MockMailSender_SendEmail_Call {
	_c.Call.Return(sendEmailOutput, err)
	return _c
}

func (_c *MockMailSender_SendEmail_Call) RunAndReturn(run func(ctx context.Context, params *ses.SendEmailInput, optFns ...func(*ses.Options)) (*ses.SendEmailOutput, error)) *MockMailSender_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendRawEmail provides a mock function for the type MockMailSender
func (_mock *MockMailSender) SendRawEmail(ctx context.Context, params *ses.SendRawEmailInput, optFns ...func(*ses.Options)) (*ses.SendRawEmailOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendRawEmail")
	}

	var r0 *ses.SendRawEmailOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ses.SendRawEmailInput, ...func(*ses.Options)) (*ses.SendRawEmailOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ses.SendRawEmailInput, ...func(*ses.Options)) *ses.SendRawEmailOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ses.SendRawEmailOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ses.SendRawEmailInput, ...func(*ses.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMailSender_SendRawEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRawEmail'
type MockMailSender_SendRawEmail_Call struct {
	*mock.Call
}

// SendRawEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ses.SendRawEmailInput
//   - optFns ...func(*ses.Options)
func (_e *MockMailSender_Expecter) SendRawEmail(ctx interface{}, params interface{}, optFns ...interface{}) *MockMailSender_SendRawEmail_Call {
	return &MockMailSender_SendRawEmail_Call{Call: _e.mock.On("SendRawEmail",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockMailSender_SendRawEmail_Call) Run(run func(ctx context.Context, params *ses.SendRawEmailInput, optFns ...func(*ses.Options))) *MockMailSender_SendRawEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ses.SendRawEmailInput
		if args[1] != nil {
			arg1 = args[1].(*ses.SendRawEmailInput)
		}
		var arg2 []func(*ses.Options)
		var variadicArgs []func(*ses.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ses.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMailSender_SendRawEmail_Call) Return(sendRawEmailOutput *ses.SendRawEmailOutput, err error) *MockMailSender_SendRawEmail_Call {
	_c.Call.Return(sendRawEmailOutput, err)
	return _c
}

func (_c *MockMailSender_SendRawEmail_Call) RunAndReturn(run func(ctx context.Context, params *ses.SendRawEmailInput, optFns ...func(*ses.Options)) (*ses.SendRawEmailOutput, error)) *MockMailSender_SendRawEmail_Call {
	_c.Call.Return(run)
	return _c
}
