// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockISCClientExtension creates a new instance of MockISCClientExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISCClientExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISCClientExtension {
	mock := &MockISCClientExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISCClientExtension is an autogenerated mock type for the ISCClientExtension type
type MockISCClientExtension struct {
	mock.Mock
}

type MockISCClientExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISCClientExtension) EXPECT() *MockISCClientExtension_Expecter {
	return &MockISCClientExtension_Expecter{mock: &_m.Mock}
}

// MakeRequest provides a mock function for the type MockISCClientExtension
func (_mock *MockISCClientExtension) MakeRequest(ctx context.Context, method string, path string, body interface{}) (*http.Response, error) {
	ret := _mock.Called(ctx, method, path, body)

	if len(ret) == 0 {
		panic("no return value specified for MakeRequest")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}) (*http.Response, error)); ok {
		return returnFunc(ctx, method, path, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}) *http.Response); ok {
		r0 = returnFunc(ctx, method, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, interface{}) error); ok {
		r1 = returnFunc(ctx, method, path, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISCClientExtension_MakeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRequest'
type MockISCClientExtension_MakeRequest_Call struct {
	*mock.Call
}

// MakeRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - body interface{}
func (_e *MockISCClientExtension_Expecter) MakeRequest(ctx interface{}, method interface{}, path interface{}, body interface{}) *MockISCClientExtension_MakeRequest_Call {
	return &MockISCClientExtension_MakeRequest_Call{Call: _e.mock.On("MakeRequest", ctx, method, path, body)}
}

func (_c *MockISCClientExtension_MakeRequest_Call) Run(run func(ctx context.Context, method string, path string, body interface{})) *MockISCClientExtension_MakeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockISCClientExtension_MakeRequest_Call) Return(response *http.Response, err error) *MockISCClientExtension_MakeRequest_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockISCClientExtension_MakeRequest_Call) RunAndReturn(run func(ctx context.Context, method string, path string, body interface{}) (*http.Response, error)) *MockISCClientExtension_MakeRequest_Call {
	_c.Call.Return(run)
	return _c
}
