// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"net/http"

	"github.com/savannahghi/authutils"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOAuthClientService creates a new instance of MockOAuthClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthClientService {
	mock := &MockOAuthClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthClientService is an autogenerated mock type for the OAuthClientService type
type MockOAuthClientService struct {
	mock.Mock
}

type MockOAuthClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthClientService) EXPECT() *MockOAuthClientService_Expecter {
	return &MockOAuthClientService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockOAuthClientService
func (_mock *MockOAuthClientService) Authenticate() (*authutils.OAUTHResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *authutils.OAUTHResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*authutils.OAUTHResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *authutils.OAUTHResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authutils.OAUTHResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthClientService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockOAuthClientService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
func (_e *MockOAuthClientService_Expecter) Authenticate() *MockOAuthClientService_Authenticate_Call {
	return &MockOAuthClientService_Authenticate_Call{Call: _e.mock.On("Authenticate")}
}

func (_c *MockOAuthClientService_Authenticate_Call) Run(run func()) *MockOAuthClientService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthClientService_Authenticate_Call) Return(oAUTHResponse *authutils.OAUTHResponse, err error) *MockOAuthClientService_Authenticate_Call {
	_c.Call.Return(oAUTHResponse, err)
	return _c
}

func (_c *MockOAuthClientService_Authenticate_Call) RunAndReturn(run func() (*authutils.OAUTHResponse, error)) *MockOAuthClientService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// HasValidSlade360BearerToken provides a mock function for the type MockOAuthClientService
func (_mock *MockOAuthClientService) HasValidSlade360BearerToken(ctx context.Context, r *http.Request) (bool, map[string]string, *authutils.TokenIntrospectionResponse) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for HasValidSlade360BearerToken")
	}

	var r0 bool
	var r1 map[string]string
	var r2 *authutils.TokenIntrospectionResponse
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) (bool, map[string]string, *authutils.TokenIntrospectionResponse)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) bool); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *http.Request) map[string]string); ok {
		r1 = returnFunc(ctx, r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *http.Request) *authutils.TokenIntrospectionResponse); ok {
		r2 = returnFunc(ctx, r)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*authutils.TokenIntrospectionResponse)
		}
	}
	return r0, r1, r2
}

// MockOAuthClientService_HasValidSlade360BearerToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasValidSlade360BearerToken'
type MockOAuthClientService_HasValidSlade360BearerToken_Call struct {
	*mock.Call
}

// HasValidSlade360BearerToken is a helper method to define mock.On call
//   - ctx context.Context
//   - r *http.Request
func (_e *MockOAuthClientService_Expecter) HasValidSlade360BearerToken(ctx interface{}, r interface{}) *MockOAuthClientService_HasValidSlade360BearerToken_Call {
	return &MockOAuthClientService_HasValidSlade360BearerToken_Call{Call: _e.mock.On("HasValidSlade360BearerToken", ctx, r)}
}

func (_c *MockOAuthClientService_HasValidSlade360BearerToken_Call) Run(run func(ctx context.Context, r *http.Request)) *MockOAuthClientService_HasValidSlade360BearerToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthClientService_HasValidSlade360BearerToken_Call) Return(b bool, stringToString map[string]string, tokenIntrospectionResponse *authutils.TokenIntrospectionResponse) *MockOAuthClientService_HasValidSlade360BearerToken_Call {
	_c.Call.Return(b, stringToString, tokenIntrospectionResponse)
	return _c
}

func (_c *MockOAuthClientService_HasValidSlade360BearerToken_Call) RunAndReturn(run func(ctx context.Context, r *http.Request) (bool, map[string]string, *authutils.TokenIntrospectionResponse)) *MockOAuthClientService_HasValidSlade360BearerToken_Call {
	_c.Call.Return(run)
	return _c
}
