// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/domain"
)

// NewMockHasFHIRSubject creates a new instance of MockHasFHIRSubject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasFHIRSubject(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasFHIRSubject {
	mock := &MockHasFHIRSubject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasFHIRSubject is an autogenerated mock type for the HasFHIRSubject type
type MockHasFHIRSubject struct {
	mock.Mock
}

type MockHasFHIRSubject_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasFHIRSubject) EXPECT() *MockHasFHIRSubject_Expecter {
	return &MockHasFHIRSubject_Expecter{mock: &_m.Mock}
}

// GetFacilityFromMeta provides a mock function for the type MockHasFHIRSubject
func (_mock *MockHasFHIRSubject) GetFacilityFromMeta() *domain.FHIRMeta {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFacilityFromMeta")
	}

	var r0 *domain.FHIRMeta
	if returnFunc, ok := ret.Get(0).(func() *domain.FHIRMeta); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FHIRMeta)
		}
	}
	return r0
}

// MockHasFHIRSubject_GetFacilityFromMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFacilityFromMeta'
type MockHasFHIRSubject_GetFacilityFromMeta_Call struct {
	*mock.Call
}

// GetFacilityFromMeta is a helper method to define mock.On call
func (_e *MockHasFHIRSubject_Expecter) GetFacilityFromMeta() *MockHasFHIRSubject_GetFacilityFromMeta_Call {
	return &MockHasFHIRSubject_GetFacilityFromMeta_Call{Call: _e.mock.On("GetFacilityFromMeta")}
}

func (_c *MockHasFHIRSubject_GetFacilityFromMeta_Call) Run(run func()) *MockHasFHIRSubject_GetFacilityFromMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHasFHIRSubject_GetFacilityFromMeta_Call) Return(fHIRMeta *domain.FHIRMeta) *MockHasFHIRSubject_GetFacilityFromMeta_Call {
	_c.Call.Return(fHIRMeta)
	return _c
}

func (_c *MockHasFHIRSubject_GetFacilityFromMeta_Call) RunAndReturn(run func() *domain.FHIRMeta) *MockHasFHIRSubject_GetFacilityFromMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubject provides a mock function for the type MockHasFHIRSubject
func (_mock *MockHasFHIRSubject) GetSubject() *domain.FHIRReference {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubject")
	}

	var r0 *domain.FHIRReference
	if returnFunc, ok := ret.Get(0).(func() *domain.FHIRReference); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FHIRReference)
		}
	}
	return r0
}

// MockHasFHIRSubject_GetSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubject'
type MockHasFHIRSubject_GetSubject_Call struct {
	*mock.Call
}

// GetSubject is a helper method to define mock.On call
func (_e *MockHasFHIRSubject_Expecter) GetSubject() *MockHasFHIRSubject_GetSubject_Call {
	return &MockHasFHIRSubject_GetSubject_Call{Call: _e.mock.On("GetSubject")}
}

func (_c *MockHasFHIRSubject_GetSubject_Call) Run(run func()) *MockHasFHIRSubject_GetSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHasFHIRSubject_GetSubject_Call) Return(fHIRReference *domain.FHIRReference) *MockHasFHIRSubject_GetSubject_Call {
	_c.Call.Return(fHIRReference)
	return _c
}

func (_c *MockHasFHIRSubject_GetSubject_Call) RunAndReturn(run func() *domain.FHIRReference) *MockHasFHIRSubject_GetSubject_Call {
	_c.Call.Return(run)
	return _c
}
