// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
)

// NewMockTimelineMapper creates a new instance of MockTimelineMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimelineMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimelineMapper {
	mock := &MockTimelineMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTimelineMapper is an autogenerated mock type for the TimelineMapper type
type MockTimelineMapper struct {
	mock.Mock
}

type MockTimelineMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimelineMapper) EXPECT() *MockTimelineMapper_Expecter {
	return &MockTimelineMapper_Expecter{mock: &_m.Mock}
}

// ToTimeline provides a mock function for the type MockTimelineMapper
func (_mock *MockTimelineMapper) ToTimeline(resource interface{}) (*dto.TimelineResource, error) {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for ToTimeline")
	}

	var r0 *dto.TimelineResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) (*dto.TimelineResource, error)); ok {
		return returnFunc(resource)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}) *dto.TimelineResource); ok {
		r0 = returnFunc(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TimelineResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = returnFunc(resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTimelineMapper_ToTimeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToTimeline'
type MockTimelineMapper_ToTimeline_Call struct {
	*mock.Call
}

// ToTimeline is a helper method to define mock.On call
//   - resource interface{}
func (_e *MockTimelineMapper_Expecter) ToTimeline(resource interface{}) *MockTimelineMapper_ToTimeline_Call {
	return &MockTimelineMapper_ToTimeline_Call{Call: _e.mock.On("ToTimeline", resource)}
}

func (_c *MockTimelineMapper_ToTimeline_Call) Run(run func(resource interface{})) *MockTimelineMapper_ToTimeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTimelineMapper_ToTimeline_Call) Return(timelineResource *dto.TimelineResource, err error) *MockTimelineMapper_ToTimeline_Call {
	_c.Call.Return(timelineResource, err)
	return _c
}

func (_c *MockTimelineMapper_ToTimeline_Call) RunAndReturn(run func(resource interface{}) (*dto.TimelineResource, error)) *MockTimelineMapper_ToTimeline_Call {
	_c.Call.Return(run)
	return _c
}
