package domain

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// FHIRActivityDefinition is documented here http://hl7.org/fhir/StructureDefinition/ActivityDefinition
type FHIRActivityDefinition struct {
	ID                           *string                          `json:"id,omitempty"`
	Meta                         *FHIRMetaInput                   `json:"meta,omitempty"`
	ImplicitRules                *string                          `json:"implicitRules,omitempty"`
	Language                     *string                          `json:"language,omitempty"`
	Text                         *FHIRNarrative                   `json:"text,omitempty"`
	Extension                    []Extension                      `json:"extension,omitempty"`
	ModifierExtension            []Extension                      `json:"modifierExtension,omitempty"`
	Url                          *string                          `json:"url,omitempty"`
	Kind                         string                           `json:"kind,omitempty"`
	Status                       PublicationStatus                `json:"status"`
	Identifier                   []FHIRIdentifier                 `json:"identifier,omitempty"`
	Version                      *string                          `json:"version,omitempty"`
	VersionAlgorithmString       *string                          `json:"versionAlgorithmString,omitempty"`
	VersionAlgorithmCoding       *FHIRCoding                      `json:"versionAlgorithmCoding,omitempty"`
	Name                         *string                          `json:"name,omitempty"`
	Title                        *string                          `json:"title,omitempty"`
	Subtitle                     *string                          `json:"subtitle,omitempty"`
	Experimental                 *bool                            `json:"experimental,omitempty"`
	SubjectCodeableConcept       *FHIRCodeableConcept             `json:"subjectCodeableConcept,omitempty"`
	SubjectReference             *Reference                       `json:"subjectReference,omitempty"`
	SubjectCanonical             *string                          `json:"subjectCanonical,omitempty"`
	Date                         *string                          `json:"date,omitempty"`
	Publisher                    *string                          `json:"publisher,omitempty"`
	Contact                      []FHIRContactDetail              `json:"contact,omitempty"`
	Description                  *string                          `json:"description,omitempty"`
	UseContext                   []FHIRUsageContext               `json:"useContext,omitempty"`
	Jurisdiction                 []FHIRCodeableConcept            `json:"jurisdiction,omitempty"`
	Purpose                      *string                          `json:"purpose,omitempty"`
	Usage                        *string                          `json:"usage,omitempty"`
	Copyright                    *string                          `json:"copyright,omitempty"`
	CopyrightLabel               *string                          `json:"copyrightLabel,omitempty"`
	ApprovalDate                 *string                          `json:"approvalDate,omitempty"`
	LastReviewDate               *string                          `json:"lastReviewDate,omitempty"`
	EffectivePeriod              *FHIRPeriod                      `json:"effectivePeriod,omitempty"`
	Topic                        []FHIRCodeableConcept            `json:"topic,omitempty"`
	Author                       []FHIRContactDetail              `json:"author,omitempty"`
	Editor                       []FHIRContactDetail              `json:"editor,omitempty"`
	Reviewer                     []FHIRContactDetail              `json:"reviewer,omitempty"`
	Endorser                     []FHIRContactDetail              `json:"endorser,omitempty"`
	RelatedArtifact              []RelatedArtifact                `json:"relatedArtifact,omitempty"`
	Library                      []string                         `json:"library,omitempty"`
	Profile                      *string                          `json:"profile,omitempty"`
	Code                         *FHIRCodeableConcept             `json:"code,omitempty"`
	DoNotPerform                 *bool                            `json:"doNotPerform,omitempty"`
	TimingTiming                 *FHIRTiming                      `json:"timingTiming,omitempty"`
	TimingAge                    *FHIRAge                         `json:"timingAge,omitempty"`
	TimingRange                  *FHIRRange                       `json:"timingRange,omitempty"`
	TimingDuration               *FHIRDuration                    `json:"timingDuration,omitempty"`
	AsNeededBoolean              *bool                            `json:"asNeededBoolean,omitempty"`
	AsNeededCodeableConcept      *FHIRCodeableConcept             `json:"asNeededCodeableConcept,omitempty"`
	Location                     *FHIRCodeableReference           `json:"location,omitempty"`
	Participant                  []ActivityDefinitionParticipant  `json:"participant,omitempty"`
	ProductReference             *FHIRReference                   `json:"productReference,omitempty"`
	ProductCodeableConcept       *FHIRCodeableConcept             `json:"productCodeableConcept,omitempty"`
	Quantity                     *FHIRQuantity                    `json:"quantity,omitempty"`
	Dosage                       []FHIRDosage                     `json:"dosage,omitempty"`
	BodySite                     []FHIRCodeableConcept            `json:"bodySite,omitempty"`
	SpecimenRequirement          []string                         `json:"specimenRequirement,omitempty"`
	ObservationRequirement       []string                         `json:"observationRequirement,omitempty"`
	ObservationResultRequirement []string                         `json:"observationResultRequirement,omitempty"`
	Transform                    *string                          `json:"transform,omitempty"`
	DynamicValue                 []ActivityDefinitionDynamicValue `json:"dynamicValue,omitempty"`
}

type ActivityDefinitionParticipant struct {
	Id                *string              `json:"id,omitempty"`
	Extension         []Extension          `json:"extension,omitempty"`
	ModifierExtension []Extension          `json:"modifierExtension,omitempty"`
	TypeCanonical     *string              `json:"typeCanonical,omitempty"`
	TypeReference     *Reference           `json:"typeReference,omitempty"`
	Role              *FHIRCodeableConcept `json:"role,omitempty"`
	Function          *FHIRCodeableConcept `json:"function,omitempty"`
}

type ActivityDefinitionDynamicValue struct {
	Id                *string        `json:"id,omitempty"`
	Extension         []Extension    `json:"extension,omitempty"`
	ModifierExtension []Extension    `json:"modifierExtension,omitempty"`
	Path              string         `json:"path"`
	Expression        FHIRExpression `json:"expression"`
}

type OtherActivityDefinition FHIRActivityDefinition
