package domain

// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// PlanDefinition is documented here http://hl7.org/fhir/StructureDefinition/PlanDefinition
type FHIRPlanDefinition struct {
	ID                      *string                `json:"id,omitempty"`
	Meta                    *FHIRMetaInput         `json:"meta,omitempty"`
	ImplicitRules           *string                `json:"implicitRules,omitempty"`
	Language                *string                `json:"language,omitempty"`
	Text                    *FHIRNarrative         `json:"text,omitempty"`
	Extension               []Extension            `json:"extension,omitempty"`
	ModifierExtension       []Extension            `json:"modifierExtension,omitempty"`
	Url                     *string                `json:"url,omitempty"`
	Identifier              []FHIRIdentifier       `json:"identifier,omitempty"`
	Version                 *string                `json:"version,omitempty"`
	VersionAlgorithmString  *string                `json:"versionAlgorithmString,omitempty"`
	VersionAlgorithmCoding  *FHIRCoding            `json:"versionAlgorithmCoding,omitempty"`
	Name                    *string                `json:"name,omitempty"`
	Title                   *string                `json:"title,omitempty"`
	Subtitle                *string                `json:"subtitle,omitempty"`
	Type                    *FHIRCodeableConcept   `json:"type,omitempty"`
	Status                  PublicationStatus      `json:"status"`
	Experimental            *bool                  `json:"experimental,omitempty"`
	SubjectCodeableConcept  *FHIRCodeableConcept   `json:"subjectCodeableConcept,omitempty"`
	SubjectReference        *Reference             `json:"subjectReference,omitempty"`
	SubjectCanonical        *string                `json:"subjectCanonical,omitempty"`
	Date                    *string                `json:"date,omitempty"`
	Publisher               *string                `json:"publisher,omitempty"`
	Contact                 []FHIRContactDetail    `json:"contact,omitempty"`
	Description             *string                `json:"description,omitempty"`
	UseContext              []FHIRUsageContext     `json:"useContext,omitempty"`
	Jurisdiction            []FHIRCodeableConcept  `json:"jurisdiction,omitempty"`
	Purpose                 *string                `json:"purpose,omitempty"`
	Usage                   *string                `json:"usage,omitempty"`
	Copyright               *string                `json:"copyright,omitempty"`
	CopyrightLabel          *string                `json:"copyrightLabel,omitempty"`
	ApprovalDate            *string                `json:"approvalDate,omitempty"`
	LastReviewDate          *string                `json:"lastReviewDate,omitempty"`
	EffectivePeriod         *FHIRPeriod            `json:"effectivePeriod,omitempty"`
	Topic                   []FHIRCodeableConcept  `json:"topic,omitempty"`
	Author                  []FHIRContactDetail    `json:"author,omitempty"`
	Editor                  []FHIRContactDetail    `json:"editor,omitempty"`
	Reviewer                []FHIRContactDetail    `json:"reviewer,omitempty"`
	Endorser                []FHIRContactDetail    `json:"endorser,omitempty"`
	RelatedArtifact         []RelatedArtifact      `json:"relatedArtifact,omitempty"`
	Library                 []string               `json:"library,omitempty"`
	Goal                    []PlanDefinitionGoal   `json:"goal,omitempty"`
	Actor                   []PlanDefinitionActor  `json:"actor,omitempty"`
	Action                  []PlanDefinitionAction `json:"action,omitempty"`
	AsNeededBoolean         *bool                  `json:"asNeededBoolean,omitempty"`
	AsNeededCodeableConcept *FHIRCodeableConcept   `json:"asNeededCodeableConcept,omitempty"`
}

type PlanDefinitionGoal struct {
	Id                *string                    `json:"id,omitempty"`
	Extension         []Extension                `json:"extension,omitempty"`
	ModifierExtension []Extension                `json:"modifierExtension,omitempty"`
	Category          *FHIRCodeableConcept       `json:"category,omitempty"`
	Description       FHIRCodeableConcept        `json:"description"`
	Priority          *FHIRCodeableConcept       `json:"priority,omitempty"`
	Start             *FHIRCodeableConcept       `json:"start,omitempty"`
	Addresses         []FHIRCodeableConcept      `json:"addresses,omitempty"`
	Documentation     []RelatedArtifact          `json:"documentation,omitempty"`
	Target            []PlanDefinitionGoalTarget `json:"target,omitempty"`
}

type PlanDefinitionGoalTarget struct {
	Id                    *string              `json:"id,omitempty"`
	Extension             []Extension          `json:"extension,omitempty"`
	ModifierExtension     []Extension          `json:"modifierExtension,omitempty"`
	Measure               *FHIRCodeableConcept `json:"measure,omitempty"`
	DetailQuantity        *FHIRQuantity        `json:"detailQuantity,omitempty"`
	DetailRange           *FHIRRange           `json:"detailRange,omitempty"`
	DetailCodeableConcept *FHIRCodeableConcept `json:"detailCodeableConcept,omitempty"`
	DetailString          *string              `json:"detailString,omitempty"`
	DetailBoolean         *bool                `json:"detailBoolean,omitempty"`
	DetailInteger         *int                 `json:"detailInteger,omitempty"`
	DetailRatio           *FHIRRatio           `json:"detailRatio,omitempty"`
	Due                   *FHIRDuration        `json:"due,omitempty"`
}

type PlanDefinitionActor struct {
	Id                *string                     `json:"id,omitempty"`
	Extension         []Extension                 `json:"extension,omitempty"`
	ModifierExtension []Extension                 `json:"modifierExtension,omitempty"`
	Title             *string                     `json:"title,omitempty"`
	Description       *string                     `json:"description,omitempty"`
	Option            []PlanDefinitionActorOption `json:"option"`
}

type PlanDefinitionActorOption struct {
	Id                *string              `json:"id,omitempty"`
	Extension         []Extension          `json:"extension,omitempty"`
	ModifierExtension []Extension          `json:"modifierExtension,omitempty"`
	TypeCanonical     *string              `json:"typeCanonical,omitempty"`
	TypeReference     *Reference           `json:"typeReference,omitempty"`
	Role              *FHIRCodeableConcept `json:"role,omitempty"`
}

type PlanDefinitionAction struct {
	Id                     *string                             `json:"id,omitempty"`
	Extension              []Extension                         `json:"extension,omitempty"`
	ModifierExtension      []Extension                         `json:"modifierExtension,omitempty"`
	LinkId                 *string                             `json:"linkId,omitempty"`
	Prefix                 *string                             `json:"prefix,omitempty"`
	Title                  *string                             `json:"title,omitempty"`
	Description            *string                             `json:"description,omitempty"`
	TextEquivalent         *string                             `json:"textEquivalent,omitempty"`
	Code                   *FHIRCodeableConcept                `json:"code,omitempty"`
	Reason                 []FHIRCodeableConcept               `json:"reason,omitempty"`
	Documentation          []RelatedArtifact                   `json:"documentation,omitempty"`
	GoalId                 []string                            `json:"goalId,omitempty"`
	SubjectCodeableConcept *FHIRCodeableConcept                `json:"subjectCodeableConcept,omitempty"`
	SubjectReference       *Reference                          `json:"subjectReference,omitempty"`
	SubjectCanonical       *string                             `json:"subjectCanonical,omitempty"`
	Condition              []PlanDefinitionActionCondition     `json:"condition,omitempty"`
	Input                  []PlanDefinitionActionInput         `json:"input,omitempty"`
	Output                 []PlanDefinitionActionOutput        `json:"output,omitempty"`
	RelatedAction          []PlanDefinitionActionRelatedAction `json:"relatedAction,omitempty"`
	TimingAge              *FHIRAge                            `json:"timingAge,omitempty"`
	TimingDuration         *FHIRDuration                       `json:"timingDuration,omitempty"`
	TimingRange            *FHIRRange                          `json:"timingRange,omitempty"`
	TimingTiming           *FHIRTiming                         `json:"timingTiming,omitempty"`
	Location               *FHIRCodeableReference              `json:"location,omitempty"`
	Participant            []PlanDefinitionActionParticipant   `json:"participant,omitempty"`
	Type                   *FHIRCodeableConcept                `json:"type,omitempty"`
	DefinitionCanonical    *string                             `json:"definitionCanonical,omitempty"`
	DefinitionUri          *string                             `json:"definitionUri,omitempty"`
	Transform              *string                             `json:"transform,omitempty"`
	DynamicValue           []PlanDefinitionActionDynamicValue  `json:"dynamicValue,omitempty"`
	Action                 []PlanDefinitionAction              `json:"action,omitempty"`
}

type PlanDefinitionActionCondition struct {
	Id                *string         `json:"id,omitempty"`
	Extension         []FHIRExtension `json:"extension,omitempty"`
	ModifierExtension []FHIRExtension `json:"modifierExtension,omitempty"`
	Expression        *FHIRExpression `json:"expression,omitempty"`
}

type PlanDefinitionActionInput struct {
	Id                *string          `json:"id,omitempty"`
	Extension         []FHIRExtension  `json:"extension,omitempty"`
	ModifierExtension []FHIRExtension  `json:"modifierExtension,omitempty"`
	Title             *string          `json:"title,omitempty"`
	Requirement       *DataRequirement `json:"requirement,omitempty"`
	RelatedData       *string          `json:"relatedData,omitempty"`
}

type PlanDefinitionActionOutput struct {
	Id                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Title             *string          `json:"title,omitempty"`
	Requirement       *DataRequirement `json:"requirement,omitempty"`
	RelatedData       *string          `json:"relatedData,omitempty"`
}

type PlanDefinitionActionRelatedAction struct {
	Id                *string       `json:"id,omitempty"`
	Extension         []Extension   `json:"extension,omitempty"`
	ModifierExtension []Extension   `json:"modifierExtension,omitempty"`
	TargetId          string        `json:"targetId"`
	OffsetDuration    *FHIRDuration `json:"offsetDuration,omitempty"`
	OffsetRange       *FHIRRange    `json:"offsetRange,omitempty"`
}

type PlanDefinitionActionParticipant struct {
	Id                *string              `json:"id,omitempty"`
	Extension         []Extension          `json:"extension,omitempty"`
	ModifierExtension []Extension          `json:"modifierExtension,omitempty"`
	ActorId           *string              `json:"actorId,omitempty"`
	TypeCanonical     *string              `json:"typeCanonical,omitempty"`
	TypeReference     *Reference           `json:"typeReference,omitempty"`
	Role              *FHIRCodeableConcept `json:"role,omitempty"`
	Function          *FHIRCodeableConcept `json:"function,omitempty"`
}

type PlanDefinitionActionDynamicValue struct {
	Id                *string         `json:"id,omitempty"`
	Extension         []FHIRExtension `json:"extension,omitempty"`
	ModifierExtension []FHIRExtension `json:"modifierExtension,omitempty"`
	Path              *string         `json:"path,omitempty"`
	Expression        *FHIRExpression `json:"expression,omitempty"`
}

// FHIRContactDetail is documented here http://hl7.org/fhir/StructureDefinition/FHIRContactDetail
type FHIRContactDetail struct {
	Id        *string            `json:"id,omitempty"`
	Extension []Extension        `json:"extension,omitempty"`
	Name      *string            `json:"name,omitempty"`
	Telecom   []FHIRContactPoint `json:"telecom,omitempty"`
}

// RelatedArtifact is documented here http://hl7.org/fhir/StructureDefinition/RelatedArtifact
type RelatedArtifact struct {
	Id                *string               `json:"id,omitempty"`
	Extension         []Extension           `json:"extension,omitempty"`
	Classifier        []FHIRCodeableConcept `json:"classifier,omitempty"`
	Label             *string               `json:"label,omitempty"`
	Display           *string               `json:"display,omitempty"`
	Citation          *string               `json:"citation,omitempty"`
	Document          *FHIRAttachment       `json:"document,omitempty"`
	Resource          *string               `json:"resource,omitempty"`
	ResourceReference *Reference            `json:"resourceReference,omitempty"`
	PublicationDate   *string               `json:"publicationDate,omitempty"`
}

type PagedFHIRPlanDefinition struct {
	PlanDefinition  []FHIRPlanDefinition `json:"planDefinition,omitempty"`
	HasNextPage     bool                 `json:"hasNextPage,omitempty"`
	NextCursor      string               `json:"nextCursor"`
	HasPreviousPage bool                 `json:"hasPreviousPage"`
	PreviousCursor  string               `json:"previousCursor"`
	TotalCount      int                  `json:"totalCount"`
}
