// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/savannahghi/empower-clinical/pkg/clinical/application/dto"
)

// NewMockAdvantageService creates a new instance of MockAdvantageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdvantageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdvantageService {
	mock := &MockAdvantageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdvantageService is an autogenerated mock type for the AdvantageService type
type MockAdvantageService struct {
	mock.Mock
}

type MockAdvantageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdvantageService) EXPECT() *MockAdvantageService_Expecter {
	return &MockAdvantageService_Expecter{mock: &_m.Mock}
}

// CreateCheckin provides a mock function for the type MockAdvantageService
func (_mock *MockAdvantageService) CreateCheckin(ctx context.Context, checkIn *dto.Checkin, headers *dto.AdvantageHeaders) error {
	ret := _mock.Called(ctx, checkIn, headers)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Checkin, *dto.AdvantageHeaders) error); ok {
		r0 = returnFunc(ctx, checkIn, headers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdvantageService_CreateCheckin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCheckin'
type MockAdvantageService_CreateCheckin_Call struct {
	*mock.Call
}

// CreateCheckin is a helper method to define mock.On call
//   - ctx context.Context
//   - checkIn *dto.Checkin
//   - headers *dto.AdvantageHeaders
func (_e *MockAdvantageService_Expecter) CreateCheckin(ctx interface{}, checkIn interface{}, headers interface{}) *MockAdvantageService_CreateCheckin_Call {
	return &MockAdvantageService_CreateCheckin_Call{Call: _e.mock.On("CreateCheckin", ctx, checkIn, headers)}
}

func (_c *MockAdvantageService_CreateCheckin_Call) Run(run func(ctx context.Context, checkIn *dto.Checkin, headers *dto.AdvantageHeaders)) *MockAdvantageService_CreateCheckin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Checkin
		if args[1] != nil {
			arg1 = args[1].(*dto.Checkin)
		}
		var arg2 *dto.AdvantageHeaders
		if args[2] != nil {
			arg2 = args[2].(*dto.AdvantageHeaders)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdvantageService_CreateCheckin_Call) Return(err error) *MockAdvantageService_CreateCheckin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdvantageService_CreateCheckin_Call) RunAndReturn(run func(ctx context.Context, checkIn *dto.Checkin, headers *dto.AdvantageHeaders) error) *MockAdvantageService_CreateCheckin_Call {
	_c.Call.Return(run)
	return _c
}

// GetSchedules provides a mock function for the type MockAdvantageService
func (_mock *MockAdvantageService) GetSchedules(ctx context.Context, headers *dto.AdvantageHeaders) ([]*dto.Schedule, error) {
	ret := _mock.Called(ctx, headers)

	if len(ret) == 0 {
		panic("no return value specified for GetSchedules")
	}

	var r0 []*dto.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AdvantageHeaders) ([]*dto.Schedule, error)); ok {
		return returnFunc(ctx, headers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AdvantageHeaders) []*dto.Schedule); ok {
		r0 = returnFunc(ctx, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AdvantageHeaders) error); ok {
		r1 = returnFunc(ctx, headers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdvantageService_GetSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSchedules'
type MockAdvantageService_GetSchedules_Call struct {
	*mock.Call
}

// GetSchedules is a helper method to define mock.On call
//   - ctx context.Context
//   - headers *dto.AdvantageHeaders
func (_e *MockAdvantageService_Expecter) GetSchedules(ctx interface{}, headers interface{}) *MockAdvantageService_GetSchedules_Call {
	return &MockAdvantageService_GetSchedules_Call{Call: _e.mock.On("GetSchedules", ctx, headers)}
}

func (_c *MockAdvantageService_GetSchedules_Call) Run(run func(ctx context.Context, headers *dto.AdvantageHeaders)) *MockAdvantageService_GetSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AdvantageHeaders
		if args[1] != nil {
			arg1 = args[1].(*dto.AdvantageHeaders)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvantageService_GetSchedules_Call) Return(schedules []*dto.Schedule, err error) *MockAdvantageService_GetSchedules_Call {
	_c.Call.Return(schedules, err)
	return _c
}

func (_c *MockAdvantageService_GetSchedules_Call) RunAndReturn(run func(ctx context.Context, headers *dto.AdvantageHeaders) ([]*dto.Schedule, error)) *MockAdvantageService_GetSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlots provides a mock function for the type MockAdvantageService
func (_mock *MockAdvantageService) GetSlots(ctx context.Context, startDate string, scheduleID string, headers *dto.AdvantageHeaders) ([]*dto.Slot, error) {
	ret := _mock.Called(ctx, startDate, scheduleID, headers)

	if len(ret) == 0 {
		panic("no return value specified for GetSlots")
	}

	var r0 []*dto.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *dto.AdvantageHeaders) ([]*dto.Slot, error)); ok {
		return returnFunc(ctx, startDate, scheduleID, headers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *dto.AdvantageHeaders) []*dto.Slot); ok {
		r0 = returnFunc(ctx, startDate, scheduleID, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *dto.AdvantageHeaders) error); ok {
		r1 = returnFunc(ctx, startDate, scheduleID, headers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdvantageService_GetSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlots'
type MockAdvantageService_GetSlots_Call struct {
	*mock.Call
}

// GetSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate string
//   - scheduleID string
//   - headers *dto.AdvantageHeaders
func (_e *MockAdvantageService_Expecter) GetSlots(ctx interface{}, startDate interface{}, scheduleID interface{}, headers interface{}) *MockAdvantageService_GetSlots_Call {
	return &MockAdvantageService_GetSlots_Call{Call: _e.mock.On("GetSlots", ctx, startDate, scheduleID, headers)}
}

func (_c *MockAdvantageService_GetSlots_Call) Run(run func(ctx context.Context, startDate string, scheduleID string, headers *dto.AdvantageHeaders)) *MockAdvantageService_GetSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *dto.AdvantageHeaders
		if args[3] != nil {
			arg3 = args[3].(*dto.AdvantageHeaders)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdvantageService_GetSlots_Call) Return(slots []*dto.Slot, err error) *MockAdvantageService_GetSlots_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockAdvantageService_GetSlots_Call) RunAndReturn(run func(ctx context.Context, startDate string, scheduleID string, headers *dto.AdvantageHeaders) ([]*dto.Slot, error)) *MockAdvantageService_GetSlots_Call {
	_c.Call.Return(run)
	return _c
}

// SegmentPatient provides a mock function for the type MockAdvantageService
func (_mock *MockAdvantageService) SegmentPatient(ctx context.Context, payload dto.SegmentationPayload) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for SegmentPatient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SegmentationPayload) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdvantageService_SegmentPatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SegmentPatient'
type MockAdvantageService_SegmentPatient_Call struct {
	*mock.Call
}

// SegmentPatient is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.SegmentationPayload
func (_e *MockAdvantageService_Expecter) SegmentPatient(ctx interface{}, payload interface{}) *MockAdvantageService_SegmentPatient_Call {
	return &MockAdvantageService_SegmentPatient_Call{Call: _e.mock.On("SegmentPatient", ctx, payload)}
}

func (_c *MockAdvantageService_SegmentPatient_Call) Run(run func(ctx context.Context, payload dto.SegmentationPayload)) *MockAdvantageService_SegmentPatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.SegmentationPayload
		if args[1] != nil {
			arg1 = args[1].(dto.SegmentationPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvantageService_SegmentPatient_Call) Return(err error) *MockAdvantageService_SegmentPatient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdvantageService_SegmentPatient_Call) RunAndReturn(run func(ctx context.Context, payload dto.SegmentationPayload) error) *MockAdvantageService_SegmentPatient_Call {
	_c.Call.Return(run)
	return _c
}

// SendSMS provides a mock function for the type MockAdvantageService
func (_mock *MockAdvantageService) SendSMS(ctx context.Context, workstationID string, branchID string, payload dto.SMSPayload) error {
	ret := _mock.Called(ctx, workstationID, branchID, payload)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dto.SMSPayload) error); ok {
		r0 = returnFunc(ctx, workstationID, branchID, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdvantageService_SendSMS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSMS'
type MockAdvantageService_SendSMS_Call struct {
	*mock.Call
}

// SendSMS is a helper method to define mock.On call
//   - ctx context.Context
//   - workstationID string
//   - branchID string
//   - payload dto.SMSPayload
func (_e *MockAdvantageService_Expecter) SendSMS(ctx interface{}, workstationID interface{}, branchID interface{}, payload interface{}) *MockAdvantageService_SendSMS_Call {
	return &MockAdvantageService_SendSMS_Call{Call: _e.mock.On("SendSMS", ctx, workstationID, branchID, payload)}
}

func (_c *MockAdvantageService_SendSMS_Call) Run(run func(ctx context.Context, workstationID string, branchID string, payload dto.SMSPayload)) *MockAdvantageService_SendSMS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 dto.SMSPayload
		if args[3] != nil {
			arg3 = args[3].(dto.SMSPayload)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdvantageService_SendSMS_Call) Return(err error) *MockAdvantageService_SendSMS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdvantageService_SendSMS_Call) RunAndReturn(run func(ctx context.Context, workstationID string, branchID string, payload dto.SMSPayload) error) *MockAdvantageService_SendSMS_Call {
	_c.Call.Return(run)
	return _c
}
